<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_service.proto

namespace Hypervel\Tests\Grpc\Fixtures;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hypervel.grpc.testing.TestRequest</code>.
 */
class TestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type string $value
     *              }
     */
    public function __construct($data = null)
    {
        \Hypervel\Tests\Grpc\Fixtures\Metadata\TestService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }
}
