<?php

declare(strict_types=1);

namespace Hypervel\Tests\Cache;

use Hypervel\Cache\RedisLock;
use Hypervel\Redis\PhpRedisConnection;
use Hypervel\Redis\RedisProxy;
use Hypervel\Tests\TestCase;
use Mockery as m;
use RuntimeException;

class RedisLockTest extends TestCase
{
    public function testAcquireWithExpirationUsesSETWithNXAndEX(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('set')
            ->once()
            ->with('lock:foo', m::type('string'), 'EX', 60, 'NX')
            ->andReturn(true);

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $this->assertTrue($lock->acquire());
    }

    public function testAcquireWithExpirationReturnsFalseWhenLockExists(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('set')
            ->once()
            ->with('lock:foo', m::type('string'), 'EX', 60, 'NX')
            ->andReturn(false);

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $this->assertFalse($lock->acquire());
    }

    public function testAcquireWithoutExpirationUsesSETNX(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('setnx')
            ->once()
            ->with('lock:foo', m::type('string'))
            ->andReturn(true);

        $lock = new RedisLock($redis, 'lock:foo', 0);

        $this->assertTrue($lock->acquire());
    }

    public function testAcquireWithoutExpirationReturnsFalseWhenLockExists(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('setnx')
            ->once()
            ->with('lock:foo', m::type('string'))
            ->andReturn(false);

        $lock = new RedisLock($redis, 'lock:foo', 0);

        $this->assertFalse($lock->acquire());
    }

    public function testReleaseUsesLuaScriptToAtomicallyCheckOwnership(): void
    {
        $connection = m::mock(PhpRedisConnection::class);
        $connection->shouldReceive('pack')
            ->once()
            ->with(['owner123'])
            ->andReturn(['packed-owner123']);
        $connection->shouldReceive('eval')
            ->once()
            ->with(m::type('string'), 1, 'lock:foo', 'packed-owner123')
            ->andReturn(1);

        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('withConnection')
            ->once()
            ->andReturnUsing(fn (callable $callback) => $callback($connection));

        $lock = new RedisLock($redis, 'lock:foo', 60, 'owner123');

        $this->assertTrue($lock->release());
    }

    public function testReleaseReturnsFalseWhenNotOwner(): void
    {
        $connection = m::mock(PhpRedisConnection::class);
        $connection->shouldReceive('pack')
            ->once()
            ->with(['owner123'])
            ->andReturn(['packed-owner123']);
        $connection->shouldReceive('eval')
            ->once()
            ->with(m::type('string'), 1, 'lock:foo', 'packed-owner123')
            ->andReturn(0);

        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('withConnection')
            ->once()
            ->andReturnUsing(fn (callable $callback) => $callback($connection));

        $lock = new RedisLock($redis, 'lock:foo', 60, 'owner123');

        $this->assertFalse($lock->release());
    }

    public function testForceReleaseDeletesKeyRegardlessOfOwnership(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('del')
            ->once()
            ->with('lock:foo');

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $lock->forceRelease();
    }

    public function testOwnerReturnsTheOwnerIdentifier(): void
    {
        $redis = m::mock(RedisProxy::class);

        $lock = new RedisLock($redis, 'lock:foo', 60, 'my-owner-id');

        $this->assertSame('my-owner-id', $lock->owner());
    }

    public function testOwnerIsAutoGeneratedWhenNotProvided(): void
    {
        $redis = m::mock(RedisProxy::class);

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $this->assertNotEmpty($lock->owner());
        $this->assertIsString($lock->owner());
    }

    public function testGetCallsAcquireAndExecutesCallbackOnSuccess(): void
    {
        $connection = m::mock(PhpRedisConnection::class);
        $connection->shouldReceive('pack')
            ->once()
            ->andReturn(['packed-owner']);
        $connection->shouldReceive('eval')
            ->once()
            ->andReturn(1);

        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('set')
            ->once()
            ->with('lock:foo', m::type('string'), 'EX', 60, 'NX')
            ->andReturn(true);
        $redis->shouldReceive('withConnection')
            ->once()
            ->andReturnUsing(fn (callable $callback) => $callback($connection));

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $result = $lock->get(fn () => 'callback-result');

        $this->assertSame('callback-result', $result);
    }

    public function testGetReturnsFalseWhenLockNotAcquired(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('set')
            ->once()
            ->with('lock:foo', m::type('string'), 'EX', 60, 'NX')
            ->andReturn(false);

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $result = $lock->get(fn () => 'callback-result');

        $this->assertFalse($result);
    }

    public function testGetReleasesLockAfterCallbackEvenOnException(): void
    {
        $connection = m::mock(PhpRedisConnection::class);
        $connection->shouldReceive('pack')
            ->once()
            ->andReturn(['packed-owner']);
        $connection->shouldReceive('eval')
            ->once()
            ->andReturn(1);

        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('set')
            ->once()
            ->andReturn(true);
        $redis->shouldReceive('withConnection')
            ->once()
            ->andReturnUsing(fn (callable $callback) => $callback($connection));

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $this->expectException(RuntimeException::class);

        $lock->get(function () {
            throw new RuntimeException('test exception');
        });
    }

    public function testGetConnectionNameReturnsConnectionName(): void
    {
        $redis = m::mock(RedisProxy::class);
        $redis->shouldReceive('getName')->once()->andReturn('default');

        $lock = new RedisLock($redis, 'lock:foo', 60);

        $this->assertSame('default', $lock->getConnectionName());
    }
}
