<?php

declare(strict_types=1);

namespace Hypervel\Tests\Testing;

use Hypervel\Testbench\TestCase;
use Hypervel\Testing\Coverage;
use PHPUnit\Framework\Attributes\Test;
use RuntimeException;
use Symfony\Component\Console\Output\BufferedOutput;

class CoverageTest extends TestCase
{
    #[Test]
    public function itFailsClearlyWhenCoverageDataWasNotGenerated(): void
    {
        $coverage = new Coverage;

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Coverage data was not generated by the test process.');

        try {
            $coverage->report(new BufferedOutput);
        } finally {
            $coverage->cleanup();
        }
    }
}
