<?php

declare(strict_types=1);

namespace Hypervel\Database;

use Exception;
use Hypervel\Database\Query\Grammars\MySqlGrammar;
use Hypervel\Database\Query\Processors\MySqlProcessor;
use Hypervel\Database\Schema\Grammars\MySqlGrammar as MySqlSchemaGrammar;
use Hypervel\Database\Schema\MySqlBuilder;
use Hypervel\Database\Schema\MySqlSchemaState;
use Hypervel\Filesystem\Filesystem;
use Hypervel\Support\Str;
use PDO;

class MySqlConnection extends Connection
{
    /**
     * The last inserted ID generated by the server.
     */
    protected string|int|null $lastInsertId = null;

    /**
     * Get a human-readable name for the given connection driver.
     */
    public function getDriverTitle(): string
    {
        return $this->isMaria() ? 'MariaDB' : 'MySQL';
    }

    /**
     * Run an insert statement against the database.
     */
    public function insert(string $query, array $bindings = [], ?string $sequence = null): bool
    {
        return $this->run($query, $bindings, function ($query, $bindings) use ($sequence) {
            if ($this->pretending()) {
                return true;
            }

            $statement = $this->getPdo()->prepare($query);

            $this->bindValues($statement, $this->prepareBindings($bindings));

            $this->recordsHaveBeenModified();

            $result = $statement->execute();

            $this->lastInsertId = $this->getPdo()->lastInsertId($sequence);

            return $result;
        });
    }

    /**
     * Escape a binary value for safe SQL embedding.
     */
    protected function escapeBinary(string $value): string
    {
        $hex = bin2hex($value);

        return "x'{$hex}'";
    }

    /**
     * Determine if the given database exception was caused by a unique constraint violation.
     */
    protected function isUniqueConstraintError(Exception $exception): bool
    {
        return (bool) preg_match('#Integrity constraint violation: 1062#i', $exception->getMessage());
    }

    /**
     * Get the connection's last insert ID.
     */
    public function getLastInsertId(): string|int|null
    {
        return $this->lastInsertId;
    }

    /**
     * Determine if the connected database is a MariaDB database.
     */
    public function isMaria(): bool
    {
        return str_contains($this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION), 'MariaDB');
    }

    /**
     * Get the server version for the connection.
     */
    public function getServerVersion(): string
    {
        return str_contains($version = parent::getServerVersion(), 'MariaDB')
            ? Str::between($version, '5.5.5-', '-MariaDB')
            : $version;
    }

    /**
     * Get the default query grammar instance.
     */
    protected function getDefaultQueryGrammar(): MySqlGrammar
    {
        return new MySqlGrammar($this);
    }

    /**
     * Get a schema builder instance for the connection.
     */
    public function getSchemaBuilder(): MySqlBuilder
    {
        if (is_null($this->schemaGrammar)) {
            $this->useDefaultSchemaGrammar();
        }

        return new MySqlBuilder($this);
    }

    /**
     * Get the default schema grammar instance.
     */
    protected function getDefaultSchemaGrammar(): MySqlSchemaGrammar
    {
        return new MySqlSchemaGrammar($this);
    }

    /**
     * Get the schema state for the connection.
     */
    #[\Override]
    public function getSchemaState(?Filesystem $files = null, ?callable $processFactory = null): MySqlSchemaState
    {
        return new MySqlSchemaState($this, $files, $processFactory);
    }

    /**
     * Get the default post processor instance.
     */
    protected function getDefaultPostProcessor(): MySqlProcessor
    {
        return new MySqlProcessor;
    }
}
