<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_service.proto

namespace Hypervel\Tests\Grpc\Fixtures\Metadata;

class TestService
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCD\x04\x0A\x12test_service.proto\x12\x15hypervel.grpc.testing\"\x1C\x0A\x0BTestRequest\x12\x0D\x0A\x05value\x18\x01 \x01(\x09\"\x1A\x0A\x09TestReply\x12\x0D\x0A\x05value\x18\x01 \x01(\x092\xE4\x02\x0A\x0BTestService\x12M\x0A\x05Unary\x12\".hypervel.grpc.testing.TestRequest\x1A .hypervel.grpc.testing.TestReply\x12V\x0A\x0CServerStream\x12\".hypervel.grpc.testing.TestRequest\x1A .hypervel.grpc.testing.TestReply0\x01\x12V\x0A\x0CClientStream\x12\".hypervel.grpc.testing.TestRequest\x1A .hypervel.grpc.testing.TestReply(\x01\x12V\x0A\x0ABidiStream\x12\".hypervel.grpc.testing.TestRequest\x1A .hypervel.grpc.testing.TestReply(\x010\x01BwZ.hypervel.dev/components/grpc-interop/testingpb\xCA\x02\x1CHypervel\\Tests\\Grpc\\Fixtures\xE2\x02%Hypervel\\Tests\\Grpc\\Fixtures\\Metadatab\x06proto3",
            true
        );

        static::$is_initialized = true;
    }
}
