<?php

declare(strict_types=1);

namespace Hypervel\Tests;

use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Hypervel\ApiClient\PendingRequest as ApiClientPendingRequest;
use Hypervel\Auth\AuthenticationException;
use Hypervel\Auth\Middleware\Authenticate;
use Hypervel\Auth\Middleware\RedirectIfAuthenticated;
use Hypervel\Auth\Notifications\ResetPassword;
use Hypervel\Auth\Notifications\VerifyEmail;
use Hypervel\Broadcasting\Broadcasters\Broadcaster;
use Hypervel\Cache\Repository as CacheRepository;
use Hypervel\Console\Application as ConsoleApplication;
use Hypervel\Console\Scheduling\Event as SchedulingEvent;
use Hypervel\Container\BoundMethod;
use Hypervel\Container\Container;
use Hypervel\Context\Context;
use Hypervel\Context\PropagatedContext;
use Hypervel\Cookie\Middleware\EncryptCookies;
use Hypervel\Coroutine\Coroutine;
use Hypervel\Database\Console\Migrations\FreshCommand;
use Hypervel\Database\Console\Migrations\RefreshCommand;
use Hypervel\Database\Console\Migrations\ResetCommand;
use Hypervel\Database\Console\Seeds\SeedCommand;
use Hypervel\Database\Console\WipeCommand;
use Hypervel\Database\DatabaseTransactionsManager;
use Hypervel\Database\Eloquent\Builder as EloquentBuilder;
use Hypervel\Database\Eloquent\Factories\Factory;
use Hypervel\Database\Eloquent\Model;
use Hypervel\Database\Eloquent\Relations\Relation;
use Hypervel\Database\Grammar;
use Hypervel\Database\Schema\Blueprint;
use Hypervel\Database\Schema\Builder as SchemaBuilder;
use Hypervel\Di\Aop\AspectCollector;
use Hypervel\Di\Aop\AspectManager;
use Hypervel\Di\Aop\AstVisitorRegistry;
use Hypervel\Di\ClassMap\ClassMapManager;
use Hypervel\Di\ReflectionManager;
use Hypervel\Foundation\Bootstrap\RegisterProviders;
use Hypervel\Foundation\Console\AboutCommand;
use Hypervel\Foundation\Console\CliDumper;
use Hypervel\Foundation\Events\DiscoverEvents;
use Hypervel\Foundation\Http\FormRequest;
use Hypervel\Foundation\Http\HtmlDumper;
use Hypervel\Foundation\Http\Middleware\ConvertEmptyStringsToNull;
use Hypervel\Foundation\Http\Middleware\PreventRequestForgery;
use Hypervel\Foundation\Http\Middleware\PreventRequestsDuringMaintenance;
use Hypervel\Foundation\Http\Middleware\TrimStrings;
use Hypervel\Foundation\Support\Providers\EventServiceProvider;
use Hypervel\Foundation\Support\Providers\RouteServiceProvider;
use Hypervel\Foundation\Testing\DatabaseConnectionResolver;
use Hypervel\Foundation\Vite;
use Hypervel\Foundation\WorkerCachedMaintenanceMode;
use Hypervel\Horizon\SupervisorCommandString;
use Hypervel\Horizon\WorkerCommandString;
use Hypervel\Http\Client\Request as HttpClientRequest;
use Hypervel\Http\Client\ResponseSequence;
use Hypervel\Http\Middleware\HandleCors;
use Hypervel\Http\Middleware\TrustHosts;
use Hypervel\Http\Middleware\TrustProxies;
use Hypervel\Http\Resources\Json\JsonResource;
use Hypervel\Http\Resources\JsonApi\JsonApiResource;
use Hypervel\Mail\Attachment;
use Hypervel\Mail\Mailer;
use Hypervel\Pagination\AbstractCursorPaginator;
use Hypervel\Pagination\AbstractPaginator;
use Hypervel\Pipeline\Pipeline;
use Hypervel\Prompts\Prompt;
use Hypervel\Queue\Console\WorkCommand;
use Hypervel\Queue\Queue;
use Hypervel\Routing\CallableDispatcher;
use Hypervel\Routing\CompiledRouteCollection;
use Hypervel\Routing\ControllerDispatcher;
use Hypervel\Routing\ImplicitRouteBinding;
use Hypervel\Routing\Middleware\ValidateSignature;
use Hypervel\Routing\ResourceRegistrar;
use Hypervel\Routing\Route;
use Hypervel\Routing\RouteSignatureParameters;
use Hypervel\Routing\SortedMiddleware;
use Hypervel\Routing\UrlGenerator;
use Hypervel\Sanctum\Sanctum;
use Hypervel\Scout\Builder as ScoutBuilder;
use Hypervel\Scout\Scout;
use Hypervel\Server\ServerManager;
use Hypervel\ServerProcess\ProcessCollector;
use Hypervel\ServerProcess\ProcessManager;
use Hypervel\Session\Middleware\AuthenticateSession;
use Hypervel\Session\Store;
use Hypervel\Support\Arr;
use Hypervel\Support\BinaryCodec;
use Hypervel\Support\Collection;
use Hypervel\Support\Composer;
use Hypervel\Support\DateFactory;
use Hypervel\Support\DotenvManager;
use Hypervel\Support\Facades\Facade;
use Hypervel\Support\Fluent;
use Hypervel\Support\Lottery;
use Hypervel\Support\Number;
use Hypervel\Support\Once;
use Hypervel\Support\ServiceProvider;
use Hypervel\Support\Sleep;
use Hypervel\Support\Str;
use Hypervel\Support\StrCache;
use Hypervel\Support\Uri;
use Hypervel\Telescope\Telescope;
use Hypervel\Testing\Fluent\AssertableJson;
use Hypervel\Testing\TestResponse;
use Hypervel\Validation\Rule;
use Hypervel\Validation\Rules\Date as DateRule;
use Hypervel\Validation\Rules\Email as EmailRule;
use Hypervel\Validation\Rules\File as FileRule;
use Hypervel\Validation\Validator;
use Hypervel\View\Component;
use Hypervel\View\Engines\CompilerEngine;
use Mockery;
use PHPUnit\Event\Test\Finished;
use PHPUnit\Event\Test\FinishedSubscriber;

/**
 * Global cleanup after every test method.
 *
 * Runs after tearDown() completes, for ALL tests regardless of base class.
 * Centralizes static state resets so individual tests don't need to remember
 * them, and prevents state leaks even when a test forgets to clean up.
 */
final class AfterEachTestSubscriber implements FinishedSubscriber
{
    public function notify(Finished $event): void
    {
        if (class_exists(Mockery::class)) {
            Mockery::close();
        }

        AboutCommand::flushState();
        AbstractCursorPaginator::flushState();
        AbstractPaginator::flushState();
        ApiClientPendingRequest::flushCache();
        Arr::flushState();
        AspectCollector::flushState();
        AspectManager::flushState();
        AssertableJson::flushState();
        AstVisitorRegistry::flushState();
        Attachment::flushState();
        Authenticate::flushState();
        AuthenticationException::flushState();
        AuthenticateSession::flushState();
        BinaryCodec::flushState();
        Blueprint::flushState();
        BoundMethod::flushMethodRecipeCache();
        Broadcaster::flushChannels();
        CacheRepository::flushState();
        CallableDispatcher::flushState();
        Carbon::resetMacros();
        Carbon::resetToStringFormat();
        Carbon::serializeUsing(null);
        Carbon::setTestNow();
        CarbonImmutable::setTestNow();
        ClassMapManager::flushState();
        CliDumper::resolveDumpSourceUsing(null);
        Collection::flushState();
        CompilerEngine::forgetCompiledOrNotExpired();
        CompiledRouteCollection::flushCache();
        Component::flushCache();
        Component::forgetComponentsResolver();
        Component::forgetFactory();
        Composer::flushState();
        ConsoleApplication::forgetBootstrappers();
        Container::setInstance(null);
        Context::flush();
        ControllerDispatcher::flushState();
        ConvertEmptyStringsToNull::flushState();
        Coroutine::flushAfterCreated();
        DatabaseConnectionResolver::flushCachedConnections();
        DatabaseTransactionsManager::flushState();
        DateFactory::useDefault();
        DateRule::flushState();
        DiscoverEvents::flushState();
        DotenvManager::flushState();
        EloquentBuilder::flushState();
        EmailRule::flushState();
        EncryptCookies::flushState();
        EventServiceProvider::flushState();
        Facade::clearResolvedInstances();
        Factory::flushState();
        FileRule::flushState();
        Fluent::flushState();
        FormRequest::flushState();
        FreshCommand::prohibit(false);
        Grammar::flushState();
        HandleCors::flushState();
        HtmlDumper::resolveDumpSourceUsing(null);
        HttpClientRequest::flushState();
        ImplicitRouteBinding::flushCache();
        JsonApiResource::flushState();
        JsonResource::flushState();
        Lottery::determineResultNormally();
        Mailer::flushState();
        Model::clearBootedModels();
        Model::flushCasterCache();
        Model::preventAccessingMissingAttributes(false);
        Model::preventLazyLoading(false);
        Model::preventSilentlyDiscardingAttributes(false);
        Model::unsetConnectionResolver();
        Model::unsetEventDispatcher();
        Number::flushState();
        Once::flushState();
        Pipeline::flushState();
        PreventRequestForgery::flushState();
        PreventRequestsDuringMaintenance::flushState();
        ProcessCollector::flushState();
        ProcessManager::flushState();
        Prompt::flushState();
        PropagatedContext::flushState();
        Queue::createPayloadUsing(null);
        RedirectIfAuthenticated::flushState();
        ReflectionManager::flushState();
        RefreshCommand::prohibit(false);
        RegisterProviders::flushState();
        Relation::flushState();
        ResetCommand::prohibit(false);
        ResetPassword::flushState();
        ResourceRegistrar::flushState();
        ResponseSequence::flushState();
        Route::flushState();
        RouteServiceProvider::flushState();
        RouteSignatureParameters::flushCache();
        Rule::flushState();
        Sanctum::flushState();
        SchedulingEvent::flushState();
        SchemaBuilder::flushState();
        Scout::flushState();
        ScoutBuilder::flushState();
        SeedCommand::prohibit(false);
        ServerManager::flushState();
        ServiceProvider::flushState();
        Sleep::flushState();
        SortedMiddleware::flushCache();
        Store::flushState();
        Str::flushState();
        StrCache::flushState();
        SupervisorCommandString::flushState();
        Telescope::flushState();
        TestResponse::flushState();
        TrimStrings::flushState();
        TrustHosts::flushState();
        TrustProxies::flushState();
        Uri::flushState();
        UrlGenerator::flushRequestState();
        ValidateSignature::flushState();
        Validator::flushState();
        VerifyEmail::flushState();
        Vite::flush();
        WipeCommand::prohibit(false);
        WorkCommand::flushState();
        WorkerCachedMaintenanceMode::flushCache();
        WorkerCommandString::flushState();
    }
}
