<?php

declare(strict_types=1);

namespace Hypervel\Support\Facades;

/**
 * @method static never abort(int $code, string $message = '', array $headers = [])
 * @method static \Hypervel\Foundation\Application addAbsoluteCachePathPrefix(string $prefix)
 * @method static void addContextualBinding(string $concrete, string $abstract, mixed $implementation)
 * @method static void afterBootstrapping(string $bootstrapper, \Closure $callback)
 * @method static void afterLoadingEnvironment(\Closure $callback)
 * @method static void afterResolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static void afterResolvingAttribute(string $attribute, \Closure $callback)
 * @method static void alias(string $abstract, string $alias)
 * @method static string basePath(string $path = '')
 * @method static void beforeBootstrapping(string $bootstrapper, \Closure $callback)
 * @method static void beforeResolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static void bind(\Closure|string $abstract, \Closure|string|null $concrete = null, bool $shared = false)
 * @method static void bindIf(\Closure|string $abstract, \Closure|string|null $concrete = null, bool $shared = false)
 * @method static void bindMethod(array|string $method, \Closure $callback)
 * @method static void boot()
 * @method static void booted(callable $callback)
 * @method static void booting(callable $callback)
 * @method static string bootstrapPath(string $path = '')
 * @method static void bootstrapWith(string[] $bootstrappers)
 * @method static bool bound(string $abstract)
 * @method static object build(string|\Closure $concrete)
 * @method static mixed buildWith(string|\Closure $concrete, array<string, mixed> $parameters = [])
 * @method static mixed call(callable|string $callback, array<string, mixed> $parameters = [], string|null $defaultMethod = null)
 * @method static mixed callMethodBinding(string $method, mixed $instance)
 * @method static string configPath(string $path = '')
 * @method static bool configurationIsCached()
 * @method static \Hypervel\Foundation\Configuration\ApplicationBuilder configure(string|null $basePath = null)
 * @method static bool currentEnvironmentIs(array<int, string>|string $environments)
 * @method static string currentLocale()
 * @method static null|string currentlyResolving()
 * @method static string databasePath(string $path = '')
 * @method static string detectEnvironment(\Closure $callback)
 * @method static \Hypervel\Foundation\Application dontMergeFrameworkConfiguration()
 * @method static string|bool environment(array|string ...$environments)
 * @method static string environmentFile()
 * @method static string environmentFilePath()
 * @method static string|null environmentPath()
 * @method static bool eventsAreCached()
 * @method static void extend(string $abstract, \Closure $closure)
 * @method static \Closure factory(string $abstract)
 * @method static void fireAfterResolvingAttributeCallbacks(\ReflectionAttribute[] $attributes, mixed $object)
 * @method static void flush()
 * @method static void flushMacros()
 * @method static void flushState()
 * @method static void forgetExtenders(string $abstract)
 * @method static void forgetInstance(string $abstract)
 * @method static void forgetInstances()
 * @method static void forgetScopedInstances()
 * @method static mixed get(string $id)
 * @method static string getAlias(string $abstract)
 * @method static array getBindings()
 * @method static string getBootstrapProvidersPath()
 * @method static string getCachedConfigPath()
 * @method static string getCachedEventsPath()
 * @method static string getCachedPackagesPath()
 * @method static string getCachedRoutesPath()
 * @method static string getFallbackLocale()
 * @method static \Hypervel\Container\Container getInstance()
 * @method static array<string, bool> getLoadedProviders()
 * @method static string getLocale()
 * @method static string getNamespace()
 * @method static \Hypervel\Support\ServiceProvider|null getProvider(\Hypervel\Support\ServiceProvider|string $provider)
 * @method static array getProviders(\Hypervel\Support\ServiceProvider|string $provider)
 * @method static int handleCommand(\Symfony\Component\Console\Input\InputInterface $input)
 * @method static bool has(string $id)
 * @method static bool hasBeenBootstrapped()
 * @method static bool hasDebugModeEnabled()
 * @method static bool hasMacro(string $name)
 * @method static bool hasMethodBinding(string $method)
 * @method static string inferBasePath()
 * @method static mixed instance(string $abstract, mixed $instance)
 * @method static bool isAlias(string $name)
 * @method static bool isBooted()
 * @method static bool isDownForMaintenance()
 * @method static bool isLocal()
 * @method static bool isLocale(string $locale)
 * @method static bool isProduction()
 * @method static bool isScoped(string $abstract)
 * @method static bool isShared(string $abstract)
 * @method static string joinPaths(string|null $basePath, string $path = '')
 * @method static string langPath(string $path = '')
 * @method static \Hypervel\Foundation\Application loadEnvironmentFrom(string $file)
 * @method static void macro(string $name, callable|object $macro)
 * @method static \Hypervel\Contracts\Foundation\MaintenanceMode maintenanceMode()
 * @method static mixed make(string $abstract, array $parameters = [])
 * @method static mixed makeWith(string $abstract, array $parameters = [])
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static string path(string $path = '')
 * @method static bool providerIsLoaded(string $provider)
 * @method static string publicPath(string $path = '')
 * @method static mixed rebinding(string $abstract, \Closure $callback)
 * @method static mixed refresh(string $abstract, mixed $target, string $method)
 * @method static \Hypervel\Support\ServiceProvider register(\Hypervel\Support\ServiceProvider|string $provider, bool $force = false)
 * @method static void registerConfiguredProviders()
 * @method static void registered(callable $callback)
 * @method static void resolveEnvironmentUsing(null|callable $callback)
 * @method static mixed resolveFromAttribute(\ReflectionAttribute $attribute, \ReflectionParameter $parameter)
 * @method static \Hypervel\Support\ServiceProvider resolveProvider(string $provider)
 * @method static void resolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static string resourcePath(string $path = '')
 * @method static bool routesAreCached()
 * @method static bool runningConsoleCommand(array|string ...$commands)
 * @method static bool runningInConsole()
 * @method static bool runningUnitTests()
 * @method static void scoped(\Closure|string $abstract, \Closure|string|null $concrete = null)
 * @method static void scopedIf(\Closure|string $abstract, \Closure|string|null $concrete = null)
 * @method static \Hypervel\Foundation\Application setBasePath(string $basePath)
 * @method static void setFallbackLocale(string $fallbackLocale)
 * @method static \Hypervel\Container\Container|null setInstance(\Hypervel\Container\Container|null $container = null)
 * @method static void setLocale(string $locale)
 * @method static void setRunningInConsole(bool $runningInConsole)
 * @method static bool shouldMergeFrameworkConfiguration()
 * @method static bool shouldSkipMiddleware()
 * @method static void singleton(\Closure|string $abstract, \Closure|string|null $concrete = null)
 * @method static void singletonIf(\Closure|string $abstract, \Closure|string|null $concrete = null)
 * @method static string storagePath(string $path = '')
 * @method static void tag(array|string $abstracts, array|string $tags)
 * @method static iterable tagged(string $tag)
 * @method static void terminate()
 * @method static \Hypervel\Foundation\Application terminating(callable|string $callback)
 * @method static \Hypervel\Foundation\Application useAppPath(string $path)
 * @method static \Hypervel\Foundation\Application useBootstrapPath(string $path)
 * @method static \Hypervel\Foundation\Application useConfigPath(string $path)
 * @method static \Hypervel\Foundation\Application useDatabasePath(string $path)
 * @method static \Hypervel\Foundation\Application useEnvironmentPath(string $path)
 * @method static \Hypervel\Foundation\Application useLangPath(string $path)
 * @method static \Hypervel\Foundation\Application usePublicPath(string $path)
 * @method static \Hypervel\Foundation\Application useStoragePath(string $path)
 * @method static string version()
 * @method static string viewPath(string $path = '')
 * @method static \Hypervel\Contracts\Container\ContextualBindingBuilder when(array|string $concrete)
 * @method static void whenHasAttribute(string $attribute, \Closure $handler)
 * @method static \Closure wrap(\Closure $callback, array $parameters = [])
 *
 * @see \Hypervel\Foundation\Application
 */
class App extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'app';
    }
}
