<?php

declare(strict_types=1);

namespace Hypervel\Support\Facades;

use Hypervel\Http\Client\Factory;

/**
 * @method static \Hypervel\Http\Client\Factory globalMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\Factory globalRequestMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\Factory globalResponseMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\Factory globalOptions(\Closure|array $options)
 * @method static \GuzzleHttp\Promise\PromiseInterface response(\GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response|callable|array|string|int|null $body = null, int $status = 200, array $headers = [])
 * @method static \Closure failedConnection(string|null $message = null)
 * @method static \Hypervel\Http\Client\ResponseSequence sequence(array $responses = [])
 * @method static \Hypervel\Http\Client\Factory fake(callable|array|null $callback = null)
 * @method static \Hypervel\Http\Client\ResponseSequence fakeSequence(string $url = '*')
 * @method static \Hypervel\Http\Client\Factory stubUrl(string $url, \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response|callable|array|string|int $callback)
 * @method static \Hypervel\Http\Client\Factory preventStrayRequests(bool $prevent = true)
 * @method static bool preventingStrayRequests()
 * @method static \Hypervel\Http\Client\Factory allowStrayRequests()
 * @method static void recordRequestResponsePair(\Hypervel\Http\Client\Request $request, \Hypervel\Http\Client\Response|null $response)
 * @method static void assertSent(callable $callback)
 * @method static void assertSentInOrder(array $callbacks)
 * @method static void assertNotSent(callable $callback)
 * @method static void assertNothingSent()
 * @method static void assertSentCount(int $count)
 * @method static void assertSequencesAreEmpty()
 * @method static \Hypervel\Support\Collection recorded(callable|null $callback = null)
 * @method static \Hypervel\Http\Client\PendingRequest createPendingRequest()
 * @method static \Hypervel\Contracts\Events\Dispatcher|null getDispatcher()
 * @method static array getGlobalMiddleware()
 * @method static \Hypervel\Http\Client\Factory registerConnection(string $name, array $config = [])
 * @method static \GuzzleHttp\ClientInterface getClient(string|null $connection, \GuzzleHttp\HandlerStack $handlerStack, array|null $config = null)
 * @method static \GuzzleHttp\ClientInterface createClient(\GuzzleHttp\HandlerStack $handlerStack)
 * @method static array getConnectionConfigs()
 * @method static array getConnectionConfig(string $name)
 * @method static \Hypervel\Http\Client\Factory setConnectionConfig(string $name, array $config)
 * @method static \Hypervel\Http\Client\Factory setReleaseCallback(string $driver, \Closure $callback)
 * @method static \Closure|null getReleaseCallback(string $driver)
 * @method static \Hypervel\Http\Client\Factory addPoolable(string $driver)
 * @method static \Hypervel\Http\Client\Factory removePoolable(string $driver)
 * @method static array getPoolables()
 * @method static \Hypervel\Http\Client\Factory setPoolables(array $poolables)
 * @method static mixed macroCall(string $method, array $parameters)
 * @method static void macro(string $name, callable|object $macro)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static bool hasMacro(string $name)
 * @method static \Hypervel\Http\Client\PendingRequest baseUrl(string $url)
 * @method static \Hypervel\Http\Client\PendingRequest withBody(\Psr\Http\Message\StreamInterface|string $content, string $contentType = 'application/json')
 * @method static \Hypervel\Http\Client\PendingRequest asJson()
 * @method static \Hypervel\Http\Client\PendingRequest asForm()
 * @method static \Hypervel\Http\Client\PendingRequest attach(array|string $name, resource|string $contents = '', string|null $filename = null, array $headers = [])
 * @method static \Hypervel\Http\Client\PendingRequest asMultipart()
 * @method static \Hypervel\Http\Client\PendingRequest bodyFormat(string $format)
 * @method static \Hypervel\Http\Client\PendingRequest withQueryParameters(array $parameters)
 * @method static \Hypervel\Http\Client\PendingRequest contentType(string $contentType)
 * @method static \Hypervel\Http\Client\PendingRequest acceptJson()
 * @method static \Hypervel\Http\Client\PendingRequest accept(string $contentType)
 * @method static \Hypervel\Http\Client\PendingRequest withHeaders(array $headers)
 * @method static \Hypervel\Http\Client\PendingRequest withHeader(string $name, mixed $value)
 * @method static \Hypervel\Http\Client\PendingRequest replaceHeaders(array $headers)
 * @method static \Hypervel\Http\Client\PendingRequest withBasicAuth(string $username, string $password)
 * @method static \Hypervel\Http\Client\PendingRequest withDigestAuth(string $username, string $password)
 * @method static \Hypervel\Http\Client\PendingRequest withToken(string $token, string $type = 'Bearer')
 * @method static \Hypervel\Http\Client\PendingRequest withUserAgent(string|bool $userAgent)
 * @method static \Hypervel\Http\Client\PendingRequest withUrlParameters(array $parameters = [])
 * @method static \Hypervel\Http\Client\PendingRequest withCookies(array $cookies, string $domain)
 * @method static \Hypervel\Http\Client\PendingRequest maxRedirects(int $max)
 * @method static \Hypervel\Http\Client\PendingRequest withoutRedirecting()
 * @method static \Hypervel\Http\Client\PendingRequest withoutVerifying()
 * @method static \Hypervel\Http\Client\PendingRequest sink(resource|string $to)
 * @method static \Hypervel\Http\Client\PendingRequest timeout(int|float $seconds)
 * @method static \Hypervel\Http\Client\PendingRequest connectTimeout(int|float $seconds)
 * @method static \Hypervel\Http\Client\PendingRequest retry(array|int $times, \Closure|int $sleepMilliseconds = 0, callable|null $when = null, bool $throw = true)
 * @method static \Hypervel\Http\Client\PendingRequest withOptions(array $options)
 * @method static \Hypervel\Http\Client\PendingRequest withMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\PendingRequest withRequestMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\PendingRequest withResponseMiddleware(callable $middleware)
 * @method static \Hypervel\Http\Client\PendingRequest beforeSending(callable $callback)
 * @method static \Hypervel\Http\Client\PendingRequest throw(callable|null $callback = null)
 * @method static \Hypervel\Http\Client\PendingRequest throwIf(callable|bool $condition)
 * @method static \Hypervel\Http\Client\PendingRequest throwUnless(callable|bool $condition)
 * @method static \Hypervel\Http\Client\PendingRequest dump()
 * @method static \Hypervel\Http\Client\PendingRequest dd()
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response get(string $url, \JsonSerializable|array|string|null $query = null)
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response head(string $url, array|string|null $query = null)
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response post(string $url, \JsonSerializable|array $data = [])
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response patch(string $url, array $data = [])
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response put(string $url, array $data = [])
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response delete(string $url, array $data = [])
 * @method static \GuzzleHttp\Promise\PromiseInterface|\Hypervel\Http\Client\Response send(string $method, string $url, array $options = [])
 * @method static \GuzzleHttp\ClientInterface buildClient()
 * @method static \GuzzleHttp\HandlerStack buildHandlerStack()
 * @method static \GuzzleHttp\HandlerStack pushHandlers(\GuzzleHttp\HandlerStack $handlerStack)
 * @method static \Closure buildBeforeSendingHandler()
 * @method static \Closure buildRecorderHandler()
 * @method static \Closure buildStubHandler()
 * @method static \Psr\Http\Message\RequestInterface runBeforeSendingCallbacks(\Psr\Http\Message\RequestInterface $request, array $options)
 * @method static array mergeOptions(mixed ...$options)
 * @method static \Hypervel\Http\Client\PendingRequest stub(\Hypervel\Support\Collection|callable $callback)
 * @method static \Hypervel\Http\Client\PendingRequest async(bool $async = true)
 * @method static \GuzzleHttp\Promise\PromiseInterface|null getPromise()
 * @method static \Hypervel\Http\Client\PendingRequest setClient(\GuzzleHttp\ClientInterface $client)
 * @method static \Hypervel\Http\Client\PendingRequest setHandler(callable $handler)
 * @method static array getOptions()
 * @method static \Hypervel\Http\Client\PendingRequest connection(string $connection, array|null $config = null)
 * @method static string|null getConnection()
 * @method static \Hypervel\Http\Client\PendingRequest|mixed when(null|\Closure|mixed $value = null, null|callable $callback = null, null|callable $default = null, null|\Closure|mixed $value = null)
 * @method static \Hypervel\Http\Client\PendingRequest|mixed unless(null|\Closure|mixed $value = null, null|callable $callback = null, null|callable $default = null, null|\Closure|mixed $value = null)
 *
 * @see \Hypervel\Http\Client\Factory
 */
class Http extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return Factory::class;
    }
}
