<?php

declare(strict_types=1);

namespace Hypervel\Support\Facades;

/**
 * @method static \Hypervel\Http\Request createFromGlobals()
 * @method static \Hypervel\Http\Request instance()
 * @method static string method()
 * @method static \Hypervel\Support\Uri uri()
 * @method static string root()
 * @method static string url()
 * @method static string fullUrl()
 * @method static string fullUrlWithQuery(array $query)
 * @method static string fullUrlWithoutQuery(array|string $keys)
 * @method static string path()
 * @method static string decodedPath()
 * @method static string|null segment(int $index, string|null $default = null)
 * @method static array segments()
 * @method static bool is(mixed ...$patterns)
 * @method static bool routeIs(mixed ...$patterns)
 * @method static bool fullUrlIs(mixed ...$patterns)
 * @method static string host()
 * @method static string httpHost()
 * @method static string schemeAndHttpHost()
 * @method static bool ajax()
 * @method static bool pjax()
 * @method static bool prefetch()
 * @method static bool secure()
 * @method static string|null ip()
 * @method static array ips()
 * @method static string|null userAgent()
 * @method static array getAcceptableContentTypes()
 * @method static \Hypervel\Http\Request merge(array $input)
 * @method static \Hypervel\Http\Request mergeIfMissing(array $input)
 * @method static \Hypervel\Http\Request replace(array $input)
 * @method static \Symfony\Component\HttpFoundation\InputBag|mixed json(string|null $key = null, mixed $default = null)
 * @method static \Hypervel\Http\Request createFrom(\Hypervel\Http\Request $from, \Hypervel\Http\Request|null $to = null)
 * @method static \Hypervel\Http\Request createFromBase(\Symfony\Component\HttpFoundation\Request $request)
 * @method static \Hypervel\Http\Request duplicate(array|null $query = null, array|null $request = null, array|null $attributes = null, array|null $cookies = null, array|null $files = null, array|null $server = null)
 * @method static bool hasSession(bool $skipIfUninitialized = false)
 * @method static \Symfony\Component\HttpFoundation\Session\SessionInterface getSession()
 * @method static \Hypervel\Contracts\Session\Session session()
 * @method static void setHypervelSession(\Hypervel\Contracts\Session\Session $session)
 * @method static void setRequestLocale(string $locale)
 * @method static void setDefaultRequestLocale(string $locale)
 * @method static mixed user(string|null $guard = null)
 * @method static null|\Hypervel\Routing\Route|object|string route(string|null $param = null, mixed $default = null)
 * @method static string fingerprint()
 * @method static \Hypervel\Http\Request setJson(\Symfony\Component\HttpFoundation\InputBag $json)
 * @method static \Closure getUserResolver()
 * @method static \Hypervel\Http\Request setUserResolver(\Closure $callback)
 * @method static \Closure getRouteResolver()
 * @method static \Hypervel\Http\Request setRouteResolver(\Closure $callback)
 * @method static array toArray()
 * @method static void initialize(array $query = [], array $request = [], array $attributes = [], array $cookies = [], array $files = [], array $server = [], string|resource|null $content = null)
 * @method static \Hypervel\Http\Request create(string $uri, string $method = 'GET', array $parameters = [], array $cookies = [], array $files = [], array $server = [], string|resource|null $content = null)
 * @method static void setFactory(callable|null $callable)
 * @method static void overrideGlobals()
 * @method static void setTrustedProxies(array $proxies, int $trustedHeaderSet)
 * @method static string[] getTrustedProxies()
 * @method static int getTrustedHeaderSet()
 * @method static void setTrustedHosts(array $hostPatterns)
 * @method static string[] getTrustedHosts()
 * @method static string normalizeQueryString(string|null $qs)
 * @method static void enableHttpMethodParameterOverride()
 * @method static bool getHttpMethodParameterOverride()
 * @method static void setAllowedHttpMethodOverride(string[]|null $methods)
 * @method static string[]|null getAllowedHttpMethodOverride()
 * @method static bool hasPreviousSession()
 * @method static void setSession(\Symfony\Component\HttpFoundation\Session\SessionInterface $session)
 * @method static array getClientIps()
 * @method static string|null getClientIp()
 * @method static string getScriptName()
 * @method static string getPathInfo()
 * @method static string getBasePath()
 * @method static string getBaseUrl()
 * @method static string getScheme()
 * @method static int|string|null getPort()
 * @method static string|null getUser()
 * @method static string|null getPassword()
 * @method static string|null getUserInfo()
 * @method static string getHttpHost()
 * @method static string getRequestUri()
 * @method static string getSchemeAndHttpHost()
 * @method static string getUri()
 * @method static string getUriForPath(string $path)
 * @method static string getRelativeUriForPath(string $path)
 * @method static string|null getQueryString()
 * @method static bool isSecure()
 * @method static string getHost()
 * @method static void setMethod(string $method)
 * @method static string getMethod()
 * @method static string getRealMethod()
 * @method static string|null getMimeType(string $format)
 * @method static string[] getMimeTypes(string $format)
 * @method static string|null getFormat(string|null $mimeType, bool $subtypeFallback = false)
 * @method static void setFormat(string $format, string|string[] $mimeTypes)
 * @method static string|null getRequestFormat(string|null $default = 'html')
 * @method static void setRequestFormat(string|null $format)
 * @method static string|null getContentTypeFormat()
 * @method static void setDefaultLocale(string $locale)
 * @method static string getDefaultLocale()
 * @method static void setLocale(string $locale)
 * @method static string getLocale()
 * @method static bool isMethod(string $method)
 * @method static bool isMethodSafe()
 * @method static bool isMethodIdempotent()
 * @method static bool isMethodCacheable()
 * @method static string|null getProtocolVersion()
 * @method static string|resource getContent(bool $asResource = false)
 * @method static \Symfony\Component\HttpFoundation\InputBag getPayload()
 * @method static array getETags()
 * @method static bool isNoCache()
 * @method static string|null getPreferredFormat(string|null $default = 'html')
 * @method static string|null getPreferredLanguage(string[]|null $locales = null)
 * @method static string[] getLanguages()
 * @method static string[] getCharsets()
 * @method static string[] getEncodings()
 * @method static bool isXmlHttpRequest()
 * @method static bool preferSafeContent()
 * @method static bool isFromTrustedProxy()
 * @method static array filterPrecognitiveRules(array $rules)
 * @method static bool isAttemptingPrecognition()
 * @method static bool isPrecognitive()
 * @method static bool isJson()
 * @method static bool expectsJson()
 * @method static bool wantsJson()
 * @method static bool accepts(array|string $contentTypes)
 * @method static string|null prefers(array|string $contentTypes)
 * @method static bool acceptsAnyContentType()
 * @method static bool acceptsJson()
 * @method static bool acceptsHtml()
 * @method static bool matchesType(string $actual, string $type)
 * @method static string format(string $default = 'html')
 * @method static array|string|null old(string|null $key = null, \Hypervel\Database\Eloquent\Model|array|string|null $default = null)
 * @method static void flash()
 * @method static void flashOnly(mixed $keys)
 * @method static void flashExcept(mixed $keys)
 * @method static void flush()
 * @method static array|string|int|float|null server(string|null $key = null, array|string|int|float|null $default = null)
 * @method static bool hasHeader(string $key)
 * @method static array|string|null header(string|null $key = null, array|string|null $default = null)
 * @method static string|null bearerToken()
 * @method static array keys()
 * @method static array all(mixed $keys = null)
 * @method static mixed input(string|null $key = null, mixed $default = null)
 * @method static \Hypervel\Support\Fluent fluent(array|string|null $key = null, array $default = [])
 * @method static array|string|null query(string|null $key = null, array|string|null $default = null)
 * @method static array|string|null post(string|null $key = null, array|string|null $default = null)
 * @method static bool hasCookie(string $key)
 * @method static array|string|null cookie(string|null $key = null, array|string|null $default = null)
 * @method static array<string, \Hypervel\Http\UploadedFile|\Hypervel\Http\UploadedFile[]> allFiles()
 * @method static bool hasFile(string $key)
 * @method static array<string, \Hypervel\Http\UploadedFile|\Hypervel\Http\UploadedFile[]>|null|\Hypervel\Http\UploadedFile|\Hypervel\Http\UploadedFile[] file(string|null $key = null, mixed $default = null)
 * @method static \Hypervel\Http\Request dump(mixed $keys = [])
 * @method static never dd(mixed ...$args)
 * @method static bool exists(array|string $key)
 * @method static bool has(array|string $key)
 * @method static bool hasAny(array|string $keys)
 * @method static \Hypervel\Http\Request|mixed whenHas(string $key, callable $callback, callable|null $default = null)
 * @method static bool filled(array|string $key)
 * @method static bool isNotFilled(array|string $key)
 * @method static bool anyFilled(array|string $keys)
 * @method static \Hypervel\Http\Request|mixed whenFilled(string $key, callable $callback, callable|null $default = null)
 * @method static bool missing(array|string $key)
 * @method static mixed whenMissing(string $key, callable $callback, callable|null $default = null)
 * @method static \Stringable str(string $key, mixed $default = null)
 * @method static \Stringable string(string $key, mixed $default = null)
 * @method static bool boolean(string|null $key = null, bool $default = false)
 * @method static int integer(string $key, int $default = 0)
 * @method static float float(string $key, float $default = 0)
 * @method static \Carbon\CarbonInterface|null date(string $key, string|null $format = null, \UnitEnum|string|null $tz = null)
 * @method static null|\BackedEnum enum(string $key, string $enumClass, null|\BackedEnum $default = null)
 * @method static \BackedEnum[] enums(string $key, string $enumClass)
 * @method static array array(array|string|null $key = null)
 * @method static \Hypervel\Support\Collection collect(array|string|null $key = null)
 * @method static array only(array|mixed $keys)
 * @method static array except(array|mixed $keys)
 * @method static \Hypervel\Http\Request|mixed when(null|\Closure|mixed $value = null, null|callable $callback = null, null|callable $default = null)
 * @method static \Hypervel\Http\Request|mixed unless(null|\Closure|mixed $value = null, null|callable $callback = null, null|callable $default = null)
 * @method static void macro(string $name, callable|object $macro)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static bool hasMacro(string $name)
 * @method static void flushMacros()
 * @method static array validate(array $rules, mixed ...$params)
 * @method static array validateWithBag(string $errorBag, array $rules, mixed ...$params)
 * @method static bool hasValidSignature(bool $absolute = true)
 * @method static bool hasValidRelativeSignature()
 * @method static bool hasValidSignatureWhileIgnoring(mixed $ignoreQuery = [], mixed $absolute = true)
 * @method static bool hasValidRelativeSignatureWhileIgnoring(mixed $ignoreQuery = [])
 * @method static bool inertia() Registered as a macro by Hypervel\Inertia\InertiaServiceProvider.
 *
 * @see \Hypervel\Http\Request
 */
class Request extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'request';
    }
}
