<?php

declare(strict_types=1);

namespace Hypervel\Support\Facades;

/**
 * @method static void addExtension(string $extension, string $engine, \Closure|null $resolver = null)
 * @method static void addLocation(string $location)
 * @method static void addLoop(mixed $data)
 * @method static \Hypervel\View\Factory addNamespace(string $namespace, array|string $hints)
 * @method static string appendSection()
 * @method static void callComposer(\Hypervel\Contracts\View\View $view)
 * @method static void callCreator(\Hypervel\Contracts\View\View $view)
 * @method static array composer(array|string $views, \Closure|string $callback)
 * @method static array composers(array $composers)
 * @method static array creator(array|string $views, \Closure|string $callback)
 * @method static void decrementRender()
 * @method static bool doneRendering()
 * @method static void endSlot()
 * @method static bool exists(string $view)
 * @method static \Hypervel\Contracts\View\View file(string $path, \Hypervel\Contracts\Support\Arrayable|array $data = [], array $mergeData = [])
 * @method static \Hypervel\Contracts\View\View first(array $views, \Hypervel\Contracts\Support\Arrayable|array $data = [], array $mergeData = [])
 * @method static void flushFinderCache()
 * @method static void flushFragments()
 * @method static void flushMacros()
 * @method static void flushSections()
 * @method static void flushStacks()
 * @method static void flushState()
 * @method static void flushStateIfDoneRendering()
 * @method static mixed getConsumableComponentData(string $key, mixed $default = null)
 * @method static \Hypervel\Contracts\Container\Container getContainer()
 * @method static \Hypervel\Contracts\Events\Dispatcher getDispatcher()
 * @method static \Hypervel\Contracts\View\Engine getEngineFromPath(string $path)
 * @method static \Hypervel\View\Engines\EngineResolver getEngineResolver()
 * @method static array getExtensions()
 * @method static \Hypervel\View\ViewFinderInterface getFinder()
 * @method static mixed getFragment(string $name, string|null $default = null)
 * @method static array getFragments()
 * @method static \stdClass|null getLastLoop()
 * @method static array getLoopStack()
 * @method static mixed getSection(string $name, string|null $default = null)
 * @method static array getSections()
 * @method static array getShared()
 * @method static bool hasMacro(string $name)
 * @method static bool hasRenderedOnce(string $id)
 * @method static bool hasSection(string $name)
 * @method static void incrementLoopIndices()
 * @method static void incrementRender()
 * @method static void inject(string $section, string $content)
 * @method static bool isStackEmpty(string $section)
 * @method static void macro(string $name, callable|object $macro)
 * @method static \Hypervel\Contracts\View\View make(string $view, \Hypervel\Contracts\Support\Arrayable|array $data = [], array $mergeData = [])
 * @method static void markAsRenderedOnce(string $id)
 * @method static array mergeSharedData(array $data)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static void notifyRendering(\Hypervel\Contracts\View\View $view)
 * @method static void observeRendering(callable $observer)
 * @method static string parentPlaceholder(string $section = '')
 * @method static void popLoop()
 * @method static void prependLocation(string $location)
 * @method static \Hypervel\View\Factory prependNamespace(string $namespace, array|string $hints)
 * @method static string renderComponent()
 * @method static string renderEach(string $view, array $data, string $iterator, string $empty = 'raw|')
 * @method static string renderTranslation()
 * @method static string renderUnless(bool $condition, string $view, \Hypervel\Contracts\Support\Arrayable|array $data = [], array $mergeData = [])
 * @method static string renderWhen(bool $condition, string $view, \Hypervel\Contracts\Support\Arrayable|array $data = [], array $mergeData = [])
 * @method static \Hypervel\View\Factory replaceNamespace(string $namespace, array|string $hints)
 * @method static bool sectionMissing(string $name)
 * @method static void setContainer(\Hypervel\Contracts\Container\Container $container)
 * @method static void setDispatcher(\Hypervel\Contracts\Events\Dispatcher $events)
 * @method static void setFinder(\Hypervel\View\ViewFinderInterface $finder)
 * @method static mixed share(array|string $key, mixed $value = null)
 * @method static mixed shared(string $key, mixed $default = null)
 * @method static void slot(string $name, string|null $content = null, array $attributes = [])
 * @method static void startComponent(\Hypervel\Contracts\View\View|\Hypervel\Contracts\Support\Htmlable|\Closure|string $view, array $data = [])
 * @method static void startComponentFirst(array $names, array $data = [])
 * @method static void startFragment(string $fragment)
 * @method static void startPrepend(string $section, string $content = '')
 * @method static void startPush(string $section, string $content = '')
 * @method static void startSection(string $section, \Hypervel\Contracts\View\View|string|null $content = null)
 * @method static void startTranslation(array $replacements = [])
 * @method static string stopFragment()
 * @method static string stopPrepend()
 * @method static string stopPush()
 * @method static string stopSection(bool $overwrite = false)
 * @method static string yieldContent(string $section, \Hypervel\Contracts\View\View|string $default = '')
 * @method static string yieldPushContent(string $section, string $default = '')
 * @method static string yieldSection()
 *
 * @see \Hypervel\View\Factory
 */
class View extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'view';
    }
}
