// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test_service.proto

package testingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_test_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestReply) Reset() {
	*x = TestReply{}
	mi := &file_test_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReply) ProtoMessage() {}

func (x *TestReply) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReply.ProtoReflect.Descriptor instead.
func (*TestReply) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{1}
}

func (x *TestReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_test_service_proto protoreflect.FileDescriptor

const file_test_service_proto_rawDesc = "" +
	"\n" +
	"\x12test_service.proto\x12\x15hypervel.grpc.testing\"#\n" +
	"\vTestRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tTestReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\xe4\x02\n" +
	"\vTestService\x12M\n" +
	"\x05Unary\x12\".hypervel.grpc.testing.TestRequest\x1a .hypervel.grpc.testing.TestReply\x12V\n" +
	"\fServerStream\x12\".hypervel.grpc.testing.TestRequest\x1a .hypervel.grpc.testing.TestReply0\x01\x12V\n" +
	"\fClientStream\x12\".hypervel.grpc.testing.TestRequest\x1a .hypervel.grpc.testing.TestReply(\x01\x12V\n" +
	"\n" +
	"BidiStream\x12\".hypervel.grpc.testing.TestRequest\x1a .hypervel.grpc.testing.TestReply(\x010\x01BwZ.hypervel.dev/components/grpc-interop/testingpb\xca\x02\x1cHypervel\\Tests\\Grpc\\Fixtures\xe2\x02%Hypervel\\Tests\\Grpc\\Fixtures\\Metadatab\x06proto3"

var (
	file_test_service_proto_rawDescOnce sync.Once
	file_test_service_proto_rawDescData []byte
)

func file_test_service_proto_rawDescGZIP() []byte {
	file_test_service_proto_rawDescOnce.Do(func() {
		file_test_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_service_proto_rawDesc), len(file_test_service_proto_rawDesc)))
	})
	return file_test_service_proto_rawDescData
}

var file_test_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_service_proto_goTypes = []any{
	(*TestRequest)(nil), // 0: hypervel.grpc.testing.TestRequest
	(*TestReply)(nil),   // 1: hypervel.grpc.testing.TestReply
}
var file_test_service_proto_depIdxs = []int32{
	0, // 0: hypervel.grpc.testing.TestService.Unary:input_type -> hypervel.grpc.testing.TestRequest
	0, // 1: hypervel.grpc.testing.TestService.ServerStream:input_type -> hypervel.grpc.testing.TestRequest
	0, // 2: hypervel.grpc.testing.TestService.ClientStream:input_type -> hypervel.grpc.testing.TestRequest
	0, // 3: hypervel.grpc.testing.TestService.BidiStream:input_type -> hypervel.grpc.testing.TestRequest
	1, // 4: hypervel.grpc.testing.TestService.Unary:output_type -> hypervel.grpc.testing.TestReply
	1, // 5: hypervel.grpc.testing.TestService.ServerStream:output_type -> hypervel.grpc.testing.TestReply
	1, // 6: hypervel.grpc.testing.TestService.ClientStream:output_type -> hypervel.grpc.testing.TestReply
	1, // 7: hypervel.grpc.testing.TestService.BidiStream:output_type -> hypervel.grpc.testing.TestReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_service_proto_init() }
func file_test_service_proto_init() {
	if File_test_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_service_proto_rawDesc), len(file_test_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_service_proto_goTypes,
		DependencyIndexes: file_test_service_proto_depIdxs,
		MessageInfos:      file_test_service_proto_msgTypes,
	}.Build()
	File_test_service_proto = out.File
	file_test_service_proto_goTypes = nil
	file_test_service_proto_depIdxs = nil
}
