<?php

declare(strict_types=1);

namespace Hypervel\Ai;

use Hypervel\Support\Facades\Facade;

/**
 * @method static \Hypervel\Ai\AiManager assertAgentNeverPrompted(string $agent)
 * @method static \Hypervel\Ai\AiManager assertAgentNeverQueued(string $agent)
 * @method static \Hypervel\Ai\AiManager assertAgentNotPrompted(string $agent, \Closure|string $callback, array|null $prompts = null, string|null $message = null)
 * @method static \Hypervel\Ai\AiManager assertAgentNotQueued(string $agent, \Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertAgentWasPrompted(string $agent, \Closure|string $callback, array|null $prompts = null, string|null $message = null)
 * @method static \Hypervel\Ai\AiManager assertAgentWasPromptedTimes(string $agent, int $times = 1)
 * @method static \Hypervel\Ai\AiManager assertAgentWasQueued(string $agent, \Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertAudioGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertAudioNotGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertAudioNotQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertAudioQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertClassified(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertEmbeddingsGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertEmbeddingsNotGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertEmbeddingsNotQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertEmbeddingsQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertFileAddedToStore(\Closure|string $storeId, string|null $fileId = null)
 * @method static \Hypervel\Ai\AiManager assertFileDeleted(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertFileNotAddedToStore(\Closure|string $storeId, string|null $fileId = null)
 * @method static \Hypervel\Ai\AiManager assertFileNotDeleted(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertFileNotRemovedFromStore(\Closure|string $storeId, string|null $fileId = null)
 * @method static \Hypervel\Ai\AiManager assertFileNotUploaded(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertFileRemovedFromStore(\Closure|string $storeId, string|null $fileId = null)
 * @method static \Hypervel\Ai\AiManager assertFileUploaded(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertImageGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertImageNotGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertImageNotQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertImageQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertNoAudioGenerated()
 * @method static \Hypervel\Ai\AiManager assertNoAudioQueued()
 * @method static \Hypervel\Ai\AiManager assertNoEmbeddingsGenerated()
 * @method static \Hypervel\Ai\AiManager assertNoEmbeddingsQueued()
 * @method static \Hypervel\Ai\AiManager assertNoFilesDeleted()
 * @method static \Hypervel\Ai\AiManager assertNoFilesUploaded()
 * @method static \Hypervel\Ai\AiManager assertNoImagesGenerated()
 * @method static \Hypervel\Ai\AiManager assertNoImagesQueued()
 * @method static \Hypervel\Ai\AiManager assertNoStoresCreated()
 * @method static \Hypervel\Ai\AiManager assertNoStoresDeleted()
 * @method static \Hypervel\Ai\AiManager assertNotClassified(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertNothingClassified()
 * @method static \Hypervel\Ai\AiManager assertNothingReranked()
 * @method static \Hypervel\Ai\AiManager assertNoTranscriptionsGenerated()
 * @method static \Hypervel\Ai\AiManager assertNoTranscriptionsQueued()
 * @method static \Hypervel\Ai\AiManager assertNotReranked(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertReranked(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertStoreCreated(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertStoreDeleted(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertStoreNotCreated(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertStoreNotDeleted(\Closure|string $callback)
 * @method static \Hypervel\Ai\AiManager assertTranscriptionGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertTranscriptionNotGenerated(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertTranscriptionNotQueued(\Closure $callback)
 * @method static \Hypervel\Ai\AiManager assertTranscriptionQueued(\Closure $callback)
 * @method static bool audioIsFaked()
 * @method static \Hypervel\Ai\Contracts\Providers\AudioProvider audioProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Providers\Provider build(array $config)
 * @method static null|\Closure captureContext()
 * @method static void captureContextUsing(\Closure $capture)
 * @method static bool classificationIsFaked()
 * @method static \Hypervel\Ai\Contracts\Providers\ClassificationProvider classificationProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static string|int|null conversationPartition()
 * @method static string|null conversationPartitionColumn()
 * @method static \Hypervel\Ai\Providers\AnthropicProvider createAnthropicDriver(array $config)
 * @method static \Hypervel\Ai\Providers\AzureOpenAiProvider createAzureDriver(array $config)
 * @method static \Hypervel\Ai\Providers\BedrockProvider createBedrockDriver(array $config)
 * @method static \Hypervel\Ai\Providers\CohereProvider createCohereDriver(array $config)
 * @method static \Hypervel\Ai\Providers\DeepSeekProvider createDeepseekDriver(array $config)
 * @method static \Hypervel\Ai\Providers\ElevenLabsProvider createElevenDriver(array $config)
 * @method static \Hypervel\Ai\Providers\GeminiProvider createGeminiDriver(array $config)
 * @method static \Hypervel\Ai\Providers\GroqProvider createGroqDriver(array $config)
 * @method static \Hypervel\Ai\Providers\JinaProvider createJinaDriver(array $config)
 * @method static \Hypervel\Ai\Providers\MistralProvider createMistralDriver(array $config)
 * @method static \Hypervel\Ai\Providers\OllamaProvider createOllamaDriver(array $config)
 * @method static \Hypervel\Ai\Providers\OpenAiCompatibleProvider createOpenaiCompatibleDriver(array $config)
 * @method static \Hypervel\Ai\Providers\OpenAiProvider createOpenaiDriver(array $config)
 * @method static \Hypervel\Ai\Providers\OpenRouterProvider createOpenrouterDriver(array $config)
 * @method static \Hypervel\Ai\Providers\TypeSafeProvider createTypesafeDriver(array $config)
 * @method static \Hypervel\Ai\Providers\VoyageAiProvider createVoyageaiDriver(array $config)
 * @method static \Hypervel\Ai\Providers\XaiProvider createXaiDriver(array $config)
 * @method static \Hypervel\Ai\Contracts\Providers\EmbeddingProvider embeddingProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static bool embeddingsAreFaked()
 * @method static string|null embeddingsCacheScope()
 * @method static \Hypervel\Ai\AiManager extend(string $name, \Closure $callback)
 * @method static \Hypervel\Ai\Contracts\Providers\AudioProvider fakeableAudioProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\ClassificationProvider fakeableClassificationProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\EmbeddingProvider fakeableEmbeddingProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\FileProvider fakeableFileProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\ImageProvider fakeableImageProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\RerankingProvider fakeableRerankingProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\StoreProvider fakeableStoreProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\TranscriptionProvider fakeableTranscriptionProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Gateway\FakeTextGateway fakeAgent(string $agent, \Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeAudioGateway fakeAudio(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeAudioGateway|null fakeAudioGateway()
 * @method static \Hypervel\Ai\Gateway\FakeClassificationGateway fakeClassification(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeClassificationGateway|null fakeClassificationGateway()
 * @method static \Hypervel\Ai\Gateway\FakeEmbeddingGateway|null fakeEmbeddingGateway()
 * @method static \Hypervel\Ai\Gateway\FakeEmbeddingGateway fakeEmbeddings(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeFileGateway|null fakeFileGateway()
 * @method static \Hypervel\Ai\Gateway\FakeFileGateway fakeFiles(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeTextGateway fakeGatewayFor(\Hypervel\Ai\Contracts\Agent $agent)
 * @method static \Hypervel\Ai\Gateway\FakeImageGateway|null fakeImageGateway()
 * @method static \Hypervel\Ai\Gateway\FakeImageGateway fakeImages(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeRerankingGateway fakeReranking(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeRerankingGateway|null fakeRerankingGateway()
 * @method static \Hypervel\Ai\Gateway\FakeStoreGateway|null fakeStoreGateway()
 * @method static \Hypervel\Ai\Gateway\FakeStoreGateway fakeStores(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Gateway\FakeTranscriptionGateway|null fakeTranscriptionGateway()
 * @method static \Hypervel\Ai\Gateway\FakeTranscriptionGateway fakeTranscriptions(\Closure|array $responses = [])
 * @method static \Hypervel\Ai\Contracts\Providers\FileProvider fileProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static bool filesAreFaked()
 * @method static void flushState()
 * @method static \Hypervel\Ai\AiManager forgetInstance(array|string|null $name = null)
 * @method static string getDefaultInstance()
 * @method static array getInstanceConfig(string $name)
 * @method static bool hasFakeGatewayFor(\Hypervel\Ai\Contracts\Agent|string $agent)
 * @method static \Hypervel\Ai\Contracts\Providers\ImageProvider imageProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static bool imagesAreFaked()
 * @method static mixed instance(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static void purge(string|null $name = null)
 * @method static \Hypervel\Ai\AiManager recordAudioGeneration(\Hypervel\Ai\Prompts\AudioPrompt|\Hypervel\Ai\Prompts\QueuedAudioPrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordClassification(\Hypervel\Ai\Prompts\ClassificationPrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordEmbeddingsGeneration(\Hypervel\Ai\Prompts\EmbeddingsPrompt|\Hypervel\Ai\Prompts\QueuedEmbeddingsPrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordFileAddition(string $storeId, string $fileId, \Hypervel\Ai\Contracts\Files\StorableFile|\Hypervel\Http\UploadedFile|\Hypervel\Ai\Contracts\Files\HasProviderId|string $file)
 * @method static \Hypervel\Ai\AiManager recordFileDeletion(string $fileId)
 * @method static \Hypervel\Ai\AiManager recordFileRemoval(string $storeId, string $fileId)
 * @method static \Hypervel\Ai\AiManager recordFileUpload(\Hypervel\Ai\Contracts\Files\StorableFile $file)
 * @method static \Hypervel\Ai\AiManager recordImageGeneration(\Hypervel\Ai\Prompts\ImagePrompt|\Hypervel\Ai\Prompts\QueuedImagePrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordPrompt(\Hypervel\Ai\Prompts\AgentPrompt|\Hypervel\Ai\QueuedAgentPrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordReranking(\Hypervel\Ai\Prompts\RerankingPrompt $prompt)
 * @method static \Hypervel\Ai\AiManager recordStoreCreation(string $name, string|null $description = null, \Hypervel\Support\Collection|null $fileIds = null, \DateInterval|null $expiresWhenIdleFor = null)
 * @method static \Hypervel\Ai\AiManager recordStoreDeletion(string $storeId)
 * @method static \Hypervel\Ai\AiManager recordTranscriptionGeneration(\Hypervel\Ai\Prompts\TranscriptionPrompt|\Hypervel\Ai\Prompts\QueuedTranscriptionPrompt $prompt)
 * @method static bool rerankingIsFaked()
 * @method static \Hypervel\Ai\Contracts\Providers\RerankingProvider rerankingProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static void resolveConversationPartitionUsing(string $column, \Closure $resolver)
 * @method static void resolveEmbeddingsCacheScopeUsing(\Closure $resolver)
 * @method static void resolveProviderConfigUsing(\Closure $resolver)
 * @method static \Hypervel\Ai\AiManager setApplication(\Hypervel\Contracts\Foundation\Application $app)
 * @method static void setDefaultInstance(string $name)
 * @method static \Hypervel\Ai\Contracts\Providers\StoreProvider storeProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static bool storesAreFaked()
 * @method static \Hypervel\Ai\Contracts\Providers\TextProvider textProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\TextProvider textProviderFor(\Hypervel\Ai\Contracts\Agent $agent, \Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static \Hypervel\Ai\Contracts\Providers\TranscriptionProvider transcriptionProvider(\Hypervel\Ai\Providers\Provider|string|null $name = null)
 * @method static bool transcriptionsAreFaked()
 *
 * @see \Hypervel\Ai\AiManager
 *
 * @mixin AiManager
 */
class Ai extends Facade
{
    /**
     * Get the registered name of the component.
     */
    protected static function getFacadeAccessor(): string
    {
        return AiManager::class;
    }
}
