#!/usr/bin/env php
<?php

declare(strict_types=1);

use Hypervel\Console\Application as ConsoleApplication;
use Hypervel\Contracts\Console\Kernel as ConsoleKernelContract;
use Hypervel\Contracts\Foundation\Application as ApplicationContract;
use Hypervel\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

ini_set('display_errors', 'on');
ini_set('display_startup_errors', 'on');
ini_set('memory_limit', '1G');

error_reporting(E_ALL);

! defined('BASE_PATH') && define('BASE_PATH', __DIR__);

$autoloadPaths = array_filter([
    getenv('HYPERVEL_AUTOLOAD_PATH') ?: null,
    BASE_PATH . '/vendor/autoload.php',
    getcwd() . '/vendor/autoload.php',
    is_string(getenv('TESTBENCH_WORKING_PATH'))
        ? (string) getenv('TESTBENCH_WORKING_PATH') . '/vendor/autoload.php'
        : null,
]);

foreach ($autoloadPaths as $autoloadPath) {
    if (is_file($autoloadPath)) {
        require $autoloadPath;
        break;
    }
}

if (! class_exists(Application::class)) {
    fwrite(STDERR, "Unable to locate Composer autoloader for the Hypervel testbench workbench.\n");
    exit(1);
}

$committedTestbenchRoot = realpath(__DIR__ . '/..');

if (
    is_string($committedTestbenchRoot)
    && is_file($committedTestbenchRoot . '/testbench.yaml')
    && is_file($committedTestbenchRoot . '/bin/testbench')
) {
    fwrite(
        STDERR,
        "This committed Testbench skeleton artisan entrypoint must not be run directly. Use php src/testbench/bin/testbench ... so Testbench boots a disposable runtime copy.\n"
    );
    exit(1);
}

! defined('SWOOLE_HOOK_FLAGS') && define('SWOOLE_HOOK_FLAGS', SWOOLE_HOOK_ALL);

$httpBootstrapCommands = ['serve', 'watch'];
$input = new ArgvInput;

if (in_array(ConsoleApplication::resolveCommandName($input), $httpBootstrapCommands, true)) {
    putenv('APP_RUNNING_IN_CONSOLE=false');
    $_ENV['APP_RUNNING_IN_CONSOLE'] = 'false';
    $_SERVER['APP_RUNNING_IN_CONSOLE'] = 'false';
}

(function () use ($input) {
    /** @var ApplicationContract $app */
    $app = require BASE_PATH . '/bootstrap/app.php';

    $kernel = $app->make(ConsoleKernelContract::class);

    $output = new ConsoleOutput;

    $status = $kernel->handle($input, $output);

    $kernel->terminate($input, $status);

    exit($status);
})();
