<?php

declare(strict_types=1);

namespace Hypervel\Sentry;

use Monolog\Formatter\FormatterInterface;
use Monolog\Formatter\LineFormatter;
use Monolog\Handler\AbstractProcessingHandler;
use Monolog\Level;
use Monolog\LogRecord;
use Sentry\Breadcrumb;
use Sentry\Event;
use Sentry\Severity;
use Sentry\State\HubInterface;
use Sentry\State\Scope;
use Throwable;
use TypeError;

class SentryHandler extends AbstractProcessingHandler
{
    /**
     * The current application environment.
     */
    protected ?string $environment = null;

    /**
     * The current version of the calling software.
     */
    protected ?string $release = null;

    /**
     * The formatter to use for the logs generated via handleBatch().
     */
    protected ?FormatterInterface $batchFormatter = null;

    /**
     * Create a new Sentry handler instance.
     *
     * @param int|Level|string $level The minimum logging level at which this handler will be triggered
     * @param bool $bubble Whether the messages that are handled can bubble up the stack or not
     * @param bool $reportExceptions If false, records with an exception in context will be ignored
     * @param bool $useFormattedMessage If true, use the formatted message instead of the raw message
     */
    public function __construct(
        protected HubInterface $hub,
        int|string|Level $level = Level::Debug,
        bool $bubble = true,
        private readonly bool $reportExceptions = true,
        private readonly bool $useFormattedMessage = false,
    ) {
        parent::__construct($level, $bubble);
    }

    public function handleBatch(array $records): void
    {
        $records = array_values(array_filter($records, $this->isHandling(...)));

        if ($records === []) {
            return;
        }

        // the record with the highest severity is the "main" one
        $record = array_reduce(
            $records,
            function (?LogRecord $highest, LogRecord $record): LogRecord {
                if ($highest === null || $record->level->value > $highest->level->value) {
                    return $record;
                }

                return $highest;
            }
        );

        // the other ones are added as a context item
        $logs = [];
        foreach ($records as $logRecord) {
            $logs[] = $this->processRecord($logRecord);
        }

        $context = $record->context;
        $context['logs'] = (string) $this->getBatchFormatter()->formatBatch($logs);

        $this->handle($record->with(context: $context));
    }

    /**
     * Set the formatter for the logs generated by handleBatch().
     */
    public function setBatchFormatter(FormatterInterface $formatter): self
    {
        $this->batchFormatter = $formatter;

        return $this;
    }

    /**
     * Get the formatter for the logs generated by handleBatch().
     */
    public function getBatchFormatter(): FormatterInterface
    {
        if (! $this->batchFormatter) {
            $this->batchFormatter = $this->getDefaultBatchFormatter();
        }

        return $this->batchFormatter;
    }

    /**
     * Translate Monolog log levels to Sentry Severity.
     */
    protected function getLogLevel(Level $logLevel): Severity
    {
        return match ($logLevel) {
            Level::Debug => Severity::debug(),
            Level::Warning => Severity::warning(),
            Level::Error => Severity::error(),
            Level::Critical, Level::Alert, Level::Emergency => Severity::fatal(),
            default => Severity::info(),
        };
    }

    /**
     * Write a log record.
     */
    protected function write(LogRecord $record): void
    {
        $this->doWrite($record);
    }

    /**
     * Write a record to Sentry.
     */
    protected function doWrite(LogRecord $record): void
    {
        $context = $record->context;
        $exception = $context['exception'] ?? null;
        $isException = $exception instanceof Throwable;
        unset($context['exception']);

        if (! $this->reportExceptions && $isException) {
            return;
        }

        $this->hub->withScope(
            function (Scope $scope) use ($record, $context, $isException, $exception): void {
                if (! empty($context)) {
                    $this->consumeContextAndApplyToScope($scope, $context);
                }

                if ($record->extra !== []) {
                    foreach ($record->extra as $key => $extra) {
                        $scope->setExtra($key, $extra);
                    }
                }

                $logger = ! empty($context['logger']) && is_string($context['logger'])
                    ? $context['logger']
                    : null;
                unset($context['logger']);

                // At this point we consumed everything we could from the context
                // what remains we add as `log_context` to the event as a whole
                if (! empty($context)) {
                    $scope->setExtra('log_context', $context);
                }

                $scope->addEventProcessor(
                    function (Event $event) use ($record, $logger): Event {
                        $event->setLevel($this->getLogLevel($record->level));
                        $event->setLogger($logger ?? $record->channel);

                        if (! empty($this->environment) && ! $event->getEnvironment()) {
                            $event->setEnvironment($this->environment);
                        }

                        if (! empty($this->release) && ! $event->getRelease()) {
                            $event->setRelease($this->release);
                        }

                        $event->setTimestamp($record->datetime->getTimestamp());

                        return $event;
                    }
                );

                if ($isException) {
                    $this->hub->captureException($exception);
                } else {
                    $this->hub->captureMessage(
                        $this->useFormattedMessage || $record->message === ''
                            ? (string) $record->formatted
                            : $record->message
                    );
                }
            }
        );
    }

    /**
     * Get the default formatter.
     */
    protected function getDefaultFormatter(): FormatterInterface
    {
        return new LineFormatter('[%channel%] %message%');
    }

    /**
     * Get the default formatter for the logs generated by handleBatch().
     */
    protected function getDefaultBatchFormatter(): FormatterInterface
    {
        return new LineFormatter;
    }

    /**
     * Set the release.
     *
     * Boot-only. Mutates the release on the worker-lifetime log handler; per-request
     * use races across coroutines and affects every subsequent log event.
     */
    public function setRelease(string $value): self
    {
        $this->release = $value;

        return $this;
    }

    /**
     * Set the current application environment.
     *
     * Boot-only. Mutates the environment on the worker-lifetime log handler;
     * per-request use races across coroutines and affects every subsequent log event.
     */
    public function setEnvironment(string $value): self
    {
        $this->environment = $value;

        return $this;
    }

    /**
     * Add a breadcrumb.
     *
     * @link https://docs.sentry.io/learn/breadcrumbs/
     */
    public function addBreadcrumb(Breadcrumb $crumb): self
    {
        $this->hub->addBreadcrumb($crumb);

        return $this;
    }

    /**
     * Consume the context and apply it to the scope.
     */
    private function consumeContextAndApplyToScope(Scope $scope, array &$context): void
    {
        if (! empty($context['extra']) && is_array($context['extra'])) {
            foreach ($context['extra'] as $key => $value) {
                $scope->setExtra($key, $value);
            }

            unset($context['extra']);
        }

        if (! empty($context['tags']) && is_array($context['tags'])) {
            foreach ($context['tags'] as $tag => $value) {
                // Ignore tags with a value that is not a string or can be casted to a string
                if (! $this->valueCanBeString($value)) {
                    continue;
                }

                $scope->setTag($tag, (string) $value);
            }

            unset($context['tags']);
        }

        if (! empty($context['fingerprint']) && is_array($context['fingerprint'])) {
            $scope->setFingerprint($context['fingerprint']);

            unset($context['fingerprint']);
        }

        if (! empty($context['user']) && is_array($context['user'])) {
            try {
                $scope->setUser($context['user']);

                unset($context['user']);
            } catch (TypeError) {
                // In some cases the context can be invalid, in that case we ignore it and
                // choose to not send it to Sentry in favor of not breaking the application
            }
        }
    }

    /**
     * Check if the value can be cast to a string.
     */
    private function valueCanBeString(mixed $value): bool
    {
        return is_string($value) || is_scalar($value) || (is_object($value) && method_exists($value, '__toString'));
    }
}
