<?php

declare(strict_types=1);

namespace Hypervel\Sentry;

use DateTimeInterface;
use Monolog\Formatter\FormatterInterface;
use Monolog\Formatter\LineFormatter;
use Monolog\Handler\AbstractProcessingHandler;
use Monolog\Logger;
use Sentry\Breadcrumb;
use Sentry\Event;
use Sentry\Monolog\CompatibilityProcessingHandlerTrait;
use Sentry\Severity;
use Sentry\State\HubInterface;
use Sentry\State\Scope;
use Throwable;
use TypeError;

class SentryHandler extends AbstractProcessingHandler
{
    use CompatibilityProcessingHandlerTrait;

    /**
     * The current application environment.
     */
    protected ?string $environment = null;

    /**
     * The current version of the calling software.
     */
    protected ?string $release = null;

    /**
     * The formatter to use for the logs generated via handleBatch().
     */
    protected ?FormatterInterface $batchFormatter = null;

    /**
     * Create a new Sentry handler instance.
     *
     * @param int|string $level The minimum logging level at which this handler will be triggered
     * @param bool $bubble Whether the messages that are handled can bubble up the stack or not
     * @param bool $reportExceptions If false, records with an exception in context will be ignored
     * @param bool $useFormattedMessage If true, use the formatted message instead of the raw message
     */
    public function __construct(
        protected HubInterface $hub,
        int|string $level = Logger::DEBUG,
        bool $bubble = true,
        private readonly bool $reportExceptions = true,
        private readonly bool $useFormattedMessage = false,
    ) {
        parent::__construct($level, $bubble);
    }

    public function handleBatch(array $records): void
    {
        $level = $this->level;

        // filter records based on their level
        $records = array_filter(
            $records,
            function ($record) use ($level) {
                return $record['level'] >= $level;
            }
        );

        if (! $records) {
            return;
        }

        // the record with the highest severity is the "main" one
        $record = array_reduce(
            $records,
            function ($highest, $record) {
                if ($highest === null || $record['level'] > $highest['level']) {
                    return $record;
                }

                return $highest;
            }
        );

        // the other ones are added as a context item
        $logs = [];
        foreach ($records as $r) {
            $logs[] = $this->processRecord($r);
        }

        if ($logs) { /* @phpstan-ignore if.alwaysTrue */
            $record['context']['logs'] = (string) $this->getBatchFormatter()->formatBatch($logs);
        }

        $this->handle($record);
    }

    /**
     * Set the formatter for the logs generated by handleBatch().
     */
    public function setBatchFormatter(FormatterInterface $formatter): self
    {
        $this->batchFormatter = $formatter;

        return $this;
    }

    /**
     * Get the formatter for the logs generated by handleBatch().
     */
    public function getBatchFormatter(): FormatterInterface
    {
        if (! $this->batchFormatter) {
            $this->batchFormatter = $this->getDefaultBatchFormatter();
        }

        return $this->batchFormatter;
    }

    /**
     * Translate Monolog log levels to Sentry Severity.
     */
    protected function getLogLevel(int $logLevel): Severity
    {
        return $this->getSeverityFromLevel($logLevel);
    }

    /**
     * Write a record to the handler.
     *
     * @suppress PhanTypeMismatchArgument
     * @param mixed $record
     */
    protected function doWrite($record): void
    {
        $exception = $record['context']['exception'] ?? null;
        $isException = $exception instanceof Throwable;
        unset($record['context']['exception']);

        if (! $this->reportExceptions && $isException) {
            return;
        }

        $this->hub->withScope(
            function (Scope $scope) use ($record, $isException, $exception) {
                $context = ! empty($record['context']) && is_array($record['context'])
                    ? $record['context']
                    : [];

                if (! empty($context)) {
                    $this->consumeContextAndApplyToScope($scope, $context);
                }

                if (! empty($record['extra']) && is_array($record['extra'])) {
                    foreach ($record['extra'] as $key => $extra) {
                        $scope->setExtra($key, $extra);
                    }
                }

                $logger = ! empty($context['logger']) && is_string($context['logger'])
                    ? $context['logger']
                    : null;
                unset($context['logger']);

                // At this point we consumed everything we could from the context
                // what remains we add as `log_context` to the event as a whole
                if (! empty($context)) {
                    $scope->setExtra('log_context', $context);
                }

                $scope->addEventProcessor(
                    function (Event $event) use ($record, $logger) {
                        $event->setLevel($this->getLogLevel($record['level']));
                        $event->setLogger($logger ?? $record['channel']);

                        if (! empty($this->environment) && ! $event->getEnvironment()) {
                            $event->setEnvironment($this->environment);
                        }

                        if (! empty($this->release) && ! $event->getRelease()) {
                            $event->setRelease($this->release);
                        }

                        if (isset($record['datetime']) && $record['datetime'] instanceof DateTimeInterface) {
                            $event->setTimestamp($record['datetime']->getTimestamp());
                        }

                        return $event;
                    }
                );

                if ($isException) {
                    $this->hub->captureException($exception);
                } else {
                    $this->hub->captureMessage(
                        $this->useFormattedMessage || empty($record['message'])
                            ? $record['formatted']
                            : $record['message']
                    );
                }
            }
        );
    }

    /**
     * Get the default formatter.
     */
    protected function getDefaultFormatter(): FormatterInterface
    {
        return new LineFormatter('[%channel%] %message%');
    }

    /**
     * Get the default formatter for the logs generated by handleBatch().
     */
    protected function getDefaultBatchFormatter(): FormatterInterface
    {
        return new LineFormatter();
    }

    /**
     * Set the release.
     */
    public function setRelease(string $value): self
    {
        $this->release = $value;

        return $this;
    }

    /**
     * Set the current application environment.
     */
    public function setEnvironment(string $value): self
    {
        $this->environment = $value;

        return $this;
    }

    /**
     * Add a breadcrumb.
     *
     * @link https://docs.sentry.io/learn/breadcrumbs/
     */
    public function addBreadcrumb(Breadcrumb $crumb): self
    {
        $this->hub->addBreadcrumb($crumb);

        return $this;
    }

    /**
     * Consume the context and apply it to the scope.
     */
    private function consumeContextAndApplyToScope(Scope $scope, array &$context): void
    {
        if (! empty($context['extra']) && is_array($context['extra'])) {
            foreach ($context['extra'] as $key => $value) {
                $scope->setExtra($key, $value);
            }

            unset($context['extra']);
        }

        if (! empty($context['tags']) && is_array($context['tags'])) {
            foreach ($context['tags'] as $tag => $value) {
                // Ignore tags with a value that is not a string or can be casted to a string
                if (! $this->valueCanBeString($value)) {
                    continue;
                }

                $scope->setTag($tag, (string) $value);
            }

            unset($context['tags']);
        }

        if (! empty($context['fingerprint']) && is_array($context['fingerprint'])) {
            $scope->setFingerprint($context['fingerprint']);

            unset($context['fingerprint']);
        }

        if (! empty($context['user']) && is_array($context['user'])) {
            try {
                $scope->setUser($context['user']);

                unset($context['user']);
            } catch (TypeError) {
                // In some cases the context can be invalid, in that case we ignore it and
                // choose to not send it to Sentry in favor of not breaking the application
            }
        }
    }

    /**
     * Check if the value can be cast to a string.
     */
    private function valueCanBeString(mixed $value): bool
    {
        return is_string($value) || is_scalar($value) || (is_object($value) && method_exists($value, '__toString'));
    }
}
