<?php

declare(strict_types=1);

namespace Hypervel\Sentry\Logs;

use Monolog\Formatter\FormatterInterface;
use Monolog\Formatter\LineFormatter;
use Monolog\Handler\AbstractProcessingHandler;
use Monolog\Level;
use Monolog\LogRecord;
use Sentry\Logs\LogLevel;
use Throwable;

class LogsHandler extends AbstractProcessingHandler
{
    /**
     * The formatter to use for the logs generated via handleBatch().
     */
    protected ?FormatterInterface $batchFormatter = null;

    public function handleBatch(array $records): void
    {
        $records = array_values(array_filter($records, $this->isHandling(...)));

        if ($records === []) {
            return;
        }

        // the record with the highest severity is the "main" one
        $record = array_reduce(
            $records,
            function (?LogRecord $highest, LogRecord $record): LogRecord {
                if ($highest === null || $record->level->value > $highest->level->value) {
                    return $record;
                }

                return $highest;
            }
        );

        // the other ones are added as a context item
        $logs = [];
        foreach ($records as $logRecord) {
            $logs[] = $this->processRecord($logRecord);
        }

        $context = $record->context;
        $context['logs'] = (string) $this->getBatchFormatter()->formatBatch($logs);

        $this->handle($record->with(context: $context));
    }

    /**
     * Set the formatter for the logs generated by handleBatch().
     */
    public function setBatchFormatter(FormatterInterface $formatter): self
    {
        $this->batchFormatter = $formatter;

        return $this;
    }

    /**
     * Get the formatter for the logs generated by handleBatch().
     */
    public function getBatchFormatter(): FormatterInterface
    {
        if (! $this->batchFormatter) {
            $this->batchFormatter = new LineFormatter;
        }

        return $this->batchFormatter;
    }

    /**
     * Write a log record.
     */
    protected function write(LogRecord $record): void
    {
        $this->doWrite($record);
    }

    /**
     * Write a record to Sentry Logs.
     */
    protected function doWrite(LogRecord $record): void
    {
        $context = $record->context;
        $exception = $context['exception'] ?? null;

        if ($exception instanceof Throwable) {
            // Unset the exception object from the log context
            unset($context['exception']);
        }

        \Sentry\logger()->aggregator()->add(
            self::getLogLevel($record->level),
            $record->message,
            [],
            array_merge($context, $record->extra, ['sentry.origin' => 'auto.logger.monolog'])
        );
    }

    /**
     * Translate a Monolog level to a Sentry log level.
     */
    private static function getLogLevel(Level $level): LogLevel
    {
        return match ($level) {
            Level::Debug => LogLevel::debug(),
            Level::Warning => LogLevel::warn(),
            Level::Error => LogLevel::error(),
            Level::Critical, Level::Alert, Level::Emergency => LogLevel::fatal(),
            default => LogLevel::info(),
        };
    }
}
