<?php

declare(strict_types=1);

namespace Hypervel\Sentry\Features;

use Hypervel\Console\Events as ConsoleEvents;
use Hypervel\Contracts\Events\Dispatcher;
use Hypervel\Sentry\Integrations\Integration;
use Sentry\Breadcrumb;
use Sentry\State\Scope;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;

class ConsoleIntegration extends Feature
{
    private const FEATURE_KEY = 'command_info';

    public function isApplicable(): bool
    {
        return true;
    }

    public function onBoot(): void
    {
        $dispatcher = $this->container->make(Dispatcher::class);

        $dispatcher->listen(ConsoleEvents\CommandStarting::class, [$this, 'commandStarting']);
        $dispatcher->listen(ConsoleEvents\CommandFinished::class, [$this, 'commandFinished']);
    }

    public function commandStarting(ConsoleEvents\CommandStarting $event): void
    {
        if (! $event->command) {
            return;
        }

        Integration::configureScope(static function (Scope $scope) use ($event): void {
            $scope->setTag('command', $event->command);
        });

        if ($this->isBreadcrumbFeatureEnabled(self::FEATURE_KEY)) {
            Integration::addBreadcrumb(new Breadcrumb(
                Breadcrumb::LEVEL_INFO,
                Breadcrumb::TYPE_DEFAULT,
                'artisan.command',
                'Starting Artisan command: ' . $event->command,
                [
                    'input' => $this->extractConsoleCommandInput($event->input),
                ]
            ));
        }
    }

    public function commandFinished(ConsoleEvents\CommandFinished $event): void
    {
        if ($this->isBreadcrumbFeatureEnabled(self::FEATURE_KEY)) {
            Integration::addBreadcrumb(new Breadcrumb(
                Breadcrumb::LEVEL_INFO,
                Breadcrumb::TYPE_DEFAULT,
                'artisan.command',
                'Finished Artisan command: ' . $event->command,
                [
                    'exit' => $event->exitCode,
                    'input' => $this->extractConsoleCommandInput($event->input),
                ]
            ));
        }

        // Flush any and all events that were possibly generated by the command
        Integration::flushEvents();

        Integration::configureScope(static function (Scope $scope): void {
            $scope->removeTag('command');
        });
    }

    /**
     * Extract the command input arguments if possible.
     */
    private function extractConsoleCommandInput(?InputInterface $input): ?string
    {
        if ($input instanceof ArgvInput) {
            return (string) $input;
        }

        return null;
    }
}
