<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/health/v1/health.proto

namespace Hypervel\Grpc\Health\V1;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthCheckResponse</code>.
 */
class HealthCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>.
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type int $status
     *           }
     */
    public function __construct($data = null)
    {
        \Hypervel\Grpc\Health\V1\Metadata\Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>.
     * @return int one of the values in {@see \Hypervel\Grpc\Health\V1\HealthCheckResponse\ServingStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>.
     * @param int $var one of the values in {@see \Hypervel\Grpc\Health\V1\HealthCheckResponse\ServingStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Hypervel\Grpc\Health\V1\HealthCheckResponse\ServingStatus::class);
        $this->status = $var;

        return $this;
    }
}
