<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/health/v1/health.proto

namespace Hypervel\Grpc\Health\V1;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthListRequest</code>.
 */
class HealthListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \Hypervel\Grpc\Health\V1\Metadata\Health::initOnce();
        parent::__construct($data);
    }
}
