<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/health/v1/health.proto

namespace Hypervel\Grpc\Health\V1;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthCheckRequest</code>.
 */
class HealthCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service = 1;</code>.
     */
    protected $service = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type string $service
     *              }
     */
    public function __construct($data = null)
    {
        \Hypervel\Grpc\Health\V1\Metadata\Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service = 1;</code>.
     * @return string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>string service = 1;</code>.
     * @return $this
     */
    public function setService(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->service = $var;

        return $this;
    }
}
