<?php

declare(strict_types=1);

namespace Hypervel\Testing;

use RuntimeException;
use SebastianBergmann\CodeCoverage\Report\Facade as CoverageReport;
use SebastianBergmann\CodeCoverage\Report\Thresholds;
use SebastianBergmann\Environment\Runtime;
use Symfony\Component\Console\Output\OutputInterface;

class Coverage
{
    /**
     * The path that PHPUnit should write serialized coverage data to.
     */
    protected string $path;

    /**
     * Create a new coverage reporter.
     */
    public function __construct()
    {
        $this->path = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'hypervel-coverage-'
            . getmypid() . '-' . bin2hex(random_bytes(6)) . '.php';
    }

    /**
     * Determine whether code coverage can be collected.
     */
    public static function isAvailable(): bool
    {
        return (new Runtime)->canCollectCodeCoverage();
    }

    /**
     * Determine whether Xdebug is the active coverage driver.
     */
    public static function usingXdebug(): bool
    {
        return (new Runtime)->hasXdebug();
    }

    /**
     * Get the path for serialized coverage data.
     */
    public function path(): string
    {
        return $this->path;
    }

    /**
     * Render the coverage report and return line coverage percentage.
     */
    public function report(OutputInterface $output): float
    {
        if (! is_file($this->path)) {
            throw new RuntimeException('Coverage data was not generated by the test process.');
        }

        /** @var array<string, mixed> $coverage */
        $coverage = require $this->path;

        $report = CoverageReport::fromSerializedData($coverage);

        $output->write($report->renderText(null, Thresholds::default(), false, false, $output->isDecorated()));

        return $report->summary()->lineCoverageAsPercentage();
    }

    /**
     * Remove temporary coverage data.
     */
    public function cleanup(): void
    {
        if (is_file($this->path)) {
            unlink($this->path);
        }
    }
}
