<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/health/v1/health.proto

namespace Hypervel\Grpc\Health\V1\Metadata;

class Health
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFE\x06\x0A\x1Bgrpc/health/v1/health.proto\x12\x0Egrpc.health.v1\"%\x0A\x12HealthCheckRequest\x12\x0F\x0A\x07service\x18\x01 \x01(\x09\"\xA9\x01\x0A\x13HealthCheckResponse\x12A\x0A\x06status\x18\x01 \x01(\x0E21.grpc.health.v1.HealthCheckResponse.ServingStatus\"O\x0A\x0DServingStatus\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x0B\x0A\x07SERVING\x10\x01\x12\x0F\x0A\x0BNOT_SERVING\x10\x02\x12\x13\x0A\x0FSERVICE_UNKNOWN\x10\x03\"\x13\x0A\x11HealthListRequest\"\xAE\x01\x0A\x12HealthListResponse\x12B\x0A\x08statuses\x18\x01 \x03(\x0B20.grpc.health.v1.HealthListResponse.StatusesEntry\x1AT\x0A\x0DStatusesEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x122\x0A\x05value\x18\x02 \x01(\x0B2#.grpc.health.v1.HealthCheckResponse:\x028\x012\xFD\x01\x0A\x06Health\x12P\x0A\x05Check\x12\".grpc.health.v1.HealthCheckRequest\x1A#.grpc.health.v1.HealthCheckResponse\x12M\x0A\x04List\x12!.grpc.health.v1.HealthListRequest\x1A\".grpc.health.v1.HealthListResponse\x12R\x0A\x05Watch\x12\".grpc.health.v1.HealthCheckRequest\x1A#.grpc.health.v1.HealthCheckResponse0\x01B\xAD\x01\x0A\x11io.grpc.health.v1B\x0BHealthProtoP\x01Z,google.golang.org/grpc/health/grpc_health_v1\xA2\x02\x0CGrpcHealthV1\xAA\x02\x0EGrpc.Health.V1\xCA\x02\x17Hypervel\\Grpc\\Health\\V1\xE2\x02 Hypervel\\Grpc\\Health\\V1\\Metadatab\x06proto3",
            true
        );

        static::$is_initialized = true;
    }
}
