<?php

declare(strict_types=1);

namespace Hypervel\Foundation\Testing\Concerns;

use Hypervel\Container\Container;
use Hypervel\Di\Aop\Aspect;
use Hypervel\Di\Aop\AspectCollector;
use Hypervel\Di\Aop\Pipeline;
use Hypervel\Di\Aop\ProceedingJoinPoint;
use Hypervel\Support\SplPriorityQueue;
use LogicException;
use ReflectionMethod;

/**
 * Provides a test helper for invoking a method through the AOP pipeline
 * without relying on generated proxies.
 *
 * In full application or Testbench integration tests, AOP proxies may already
 * be generated and those tests should call the target method normally. This
 * trait is for tests where the target is not already proxied, or where the
 * goal is to exercise aspect pipeline behavior directly.
 *
 * callWithAspects() builds a ProceedingJoinPoint for the target method and runs
 * it through the same aspect resolution and pipeline execution flow used by
 * generated proxies before invoking the original method via reflection.
 */
trait InteractsWithAop
{
    /**
     * Determine if the given instance is already running through an AOP proxy.
     *
     * This is useful in tests that need to handle both execution paths
     * explicitly. In isolated runs, the target class may be proxied during
     * bootstrap and should be called normally. In larger test runs, load order
     * may mean the original class was loaded before proxy generation, so the
     * test must use callWithAspects() instead.
     *
     * Keeping this check separate makes it clear whether the test is using the
     * real proxy path or the manual pipeline path.
     */
    protected function isAopProxied(object $instance): bool
    {
        return method_exists($instance, '__proxyCall');
    }

    /**
     * Call a method through the registered AOP aspect pipeline.
     *
     * Builds a ProceedingJoinPoint for the given instance and method, resolves
     * matching aspects from AspectCollector, and executes them in priority order.
     * The original method is called via reflection at the end of the pipeline.
     * The instance must not already be proxied.
     *
     * @param object $instance The object instance to call the method on
     * @param string $method The method name to intercept
     * @param array $arguments Method arguments as key => value pairs (parameter names as keys)
     */
    protected function callWithAspects(object $instance, string $method, array $arguments = []): mixed
    {
        $className = $instance::class;

        if ($this->isAopProxied($instance)) {
            throw new LogicException(
                "Cannot use callWithAspects() on {$className}::{$method} — the class is already proxied by AOP. "
                . 'Call the method normally and the proxy will intercept it automatically.'
            );
        }

        $reflectionMethod = new ReflectionMethod($className, $method);

        $formattedArguments = $this->buildAopArguments($reflectionMethod, $arguments);
        $originalMethod = $reflectionMethod->getClosure($instance);

        $joinPoint = new ProceedingJoinPoint(
            $originalMethod,
            $className,
            $method,
            $formattedArguments
        );

        $aspects = $this->resolveMatchingAspects($className, $method);

        if (empty($aspects)) {
            return $joinPoint->processOriginalMethod();
        }

        return (new Pipeline(Container::getInstance()))
            ->via('process')
            ->through($aspects)
            ->send($joinPoint)
            ->then(fn (ProceedingJoinPoint $point) => $point->processOriginalMethod());
    }

    /**
     * Build the argument structure that ProceedingJoinPoint expects.
     *
     * Mirrors the structure generated by ProxyCallVisitor:
     * ['order' => [...names], 'keys' => [...name => value], 'variadic' => 'paramName']
     *
     * Fills in default values for omitted optional parameters and identifies
     * variadic parameters so ProceedingJoinPoint::getArguments() can unpack them.
     */
    private function buildAopArguments(ReflectionMethod $method, array $provided): array
    {
        $order = [];
        $keys = [];
        $variadic = '';

        foreach ($method->getParameters() as $param) {
            $name = $param->getName();
            $order[] = $name;

            if ($param->isVariadic()) {
                $variadic = $name;
                $keys[$name] = $provided[$name] ?? [];
            } elseif (array_key_exists($name, $provided)) {
                $keys[$name] = $provided[$name];
            } elseif ($param->isDefaultValueAvailable()) {
                $keys[$name] = $param->getDefaultValue();
            }
        }

        return [
            'order' => $order,
            'keys' => $keys,
            'variadic' => $variadic,
        ];
    }

    /**
     * Resolve the aspects that match the given class and method, sorted by priority.
     *
     * @return array<int, string> Aspect class names in priority order
     */
    private function resolveMatchingAspects(string $className, string $method): array
    {
        $allAspects = AspectCollector::get('classes', []);
        $matched = [];

        foreach ($allAspects as $aspect => $rules) {
            foreach ($rules as $rule) {
                if (Aspect::isMatch($className, $method, $rule)) {
                    $matched[] = $aspect;
                    break;
                }
            }
        }

        if (empty($matched)) {
            return [];
        }

        $queue = new SplPriorityQueue;
        foreach ($matched as $aspect) {
            $queue->insert($aspect, AspectCollector::getPriority($aspect));
        }

        $sorted = [];
        while ($queue->valid()) {
            $sorted[] = $queue->current();
            $queue->next();
        }

        return $sorted;
    }
}
