name: engine

on:
  push:
    branches:
      - 0.4
  pull_request:

env:
  RUN_BLOCKING_TESTS: true

jobs:
  engine:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: ghcr.io/hypervel/components-ci:php${{ matrix.php }}-swoole6.2.2

    strategy:
      fail-fast: false
      matrix:
        php: ["8.4", "8.5"]

    name: Engine Integration Tests (PHP ${{ matrix.php }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Log trigger context
        uses: ./.github/actions/log-trigger-context

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: /root/.composer/cache
          key: composer-${{ matrix.php }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-${{ matrix.php }}-

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist -n -o

      - name: Start test servers
        uses: ./.github/actions/start-test-servers
        with:
          group: engine

      - name: Execute integration tests
        env:
          TEST_SERVER_HOST: 127.0.0.1
        run: |
          vendor/bin/paratest tests/Integration/Engine
          vendor/bin/paratest tests/Integration/HttpServer
          vendor/bin/paratest tests/Integration/Saloon
