name: static analysis

on:
  push:
    branches:
      - 0.4
  pull_request:

jobs:
  types:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Source Code
            config: phpstan.neon.dist
          - name: Types
            config: phpstan.types.neon.dist

    name: ${{ matrix.name }}

    container:
      image: ghcr.io/hypervel/components-ci:php8.4-swoole6.2.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Log trigger context
        uses: ./.github/actions/log-trigger-context

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: /root/.composer/cache
          key: composer-8.4-${{ hashFiles('composer.lock') }}
          restore-keys: composer-8.4-

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction --no-progress

      - name: Execute type checking
        run: vendor/bin/phpstan --configuration="${{ matrix.config }}" --memory-limit=-1 --no-progress
