<?php

declare(strict_types=1);

namespace Hypervel\Testbench\Factories;

use Hypervel\Database\Eloquent\Factories\Factory;
use Hypervel\Foundation\Auth\User;
use Hypervel\Support\Facades\Hash;
use Hypervel\Support\Str;

/**
 * @phpstan-type TModel \Hypervel\Foundation\Auth\User
 *
 * @extends \Hypervel\Database\Eloquent\Factories\Factory<TModel>
 *
 * @property null|class-string<\Hypervel\Database\Eloquent\Model|TModel> $model
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password = null;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Hypervel\Database\Eloquent\Model|TModel>
     */
    public function modelName(): string
    {
        return $this->model ?? config('auth.providers.users.model') ?? User::class;
    }
}
